### ISSUE TITLE
Mask log-messages

### ISSUE THREAD

**Issue by OllisGit** [OllisGit/OctoPrint-SpoolManager#107]
Like passwords and urls

**Comment by PowerWiesel** [comment]
Hey :smile: 
I was about to report that passwords are leaked in the logs and saw that you already have this ticket.
I don't use your plugin but I guess the Olli user is the default one? 
If everybody got the same user it's not that bad but if somebody changes the credentials and uploads the logs in a ticket or on the forum it wouldn't be so great.

**Comment by OllisGit** [comment]
In next release the connection settings logs are only printed, if sql logging is enabled (only for debugging)

**Comment by OllisGit** [comment]
Hi,
in the latest version the issue should be fixed. Only visible if SQL logging is enabled.
Please test and give a feedback.

Thx in advance
Olli
