### ISSUE TITLE
DB Error after update to 1.3.2

### ISSUE THREAD

**Issue by StevenK2104** [OllisGit/OctoPrint-SpoolManager#109]
Getting this error now after I updated to 1.3.2

ERROR: SPM:DatabaseManager
Database call error in methode loadSpool. See OctoPrint.log for details!

Log file below

[octoprint.log](https://github.com/OllisGit/OctoPrint-SpoolManager/files/5868896/octoprint.log)
![firefox_mGw4Pp0zFo](https://user-images.githubusercontent.com/77988939/105751227-a1f89a00-5f3d-11eb-8ab5-6b6a9e75b037.png)

**Comment by StanDH** [comment]
Identical Problem.

**Comment by StevenK2104** [comment]
any idea on how long this will be till the issue is fixed ?

**Comment by OllisGit** [comment]
Hi @StevenK2104 ,

the log messages of the db-migration looks good. Please do the following:

- login to your raspberry via ssh
- navigate to the database-location (found in plugin-settings)
- type ```sqlite3 spoolmanager.db```
- type ```select * from spo_spoolmodel```
- paste the result to this issue
- type ```select * from spo_pluginmetadatamodel```
- paste the result to this issue

btw. "Impossible is done immediately, miracles take longer"

**Comment by OllisGit** [comment]
Hi,
fyi: found the issue, will be fixed in the next minutes!

**Comment by vdibenedetto** [comment]
pi@octopi:~/.octoprint/data/SpoolManager $ sqlite3 spoolmanager.db
-bash: sqlite3: command not found

**Comment by schwos** [comment]
Experience the same issue; as well sqlite3 isn't installed natively on the Raspberry PI install in the image. It was necessary to install sqlite3 on my image

sudo apt-get install sqlite3

**Comment by OllisGit** [comment]
Error is fixed in lates release 1.3.3.
Please test and give feedback.

Sorry,
Olli

**Comment by StevenK2104** [comment]
Issue now resolved.
Many thanks @OllisGit for the great work on this

**Comment by vdibenedetto** [comment]
It works, thank you!
