### ISSUE TITLE
Show remaining filament in the spool dropdown menu

### ISSUE THREAD

**Issue by d4rken** [OllisGit/OctoPrint-SpoolManager#11]
It would be useful to see how much filament is left on a spool when selecting one in the dropdown menu. This would help me select the right spool.

![Screenshot from 2020-07-17 09-53-18](https://user-images.githubusercontent.com/1439229/87762394-5d17dc00-c813-11ea-82f5-626fa7ec93f3.png)

**Comment by OllisGit** [comment]
Hii @d4rken ,

good idea! Will be available in the next release.

**Comment by OllisGit** [comment]
Hi @d4rken ,

it is implemented in RC3.

Please test and give feedback.

Thx, in advance
Olli

**Comment by d4rken** [comment]
It shows usage, but the values are too large (>100%):

```html
<option value="">Select Spool...</option>
<option value=""> - Prusament PLA - AzureBlue 1 (398.4%)</option>
<option value=""> - Prusament PETG - GalaxyBlack 1 (452.3%)</option>
<option value="">black - Prusament PETG - JetBlack 3 (990.7%)</option>
<option value=""> - Prusament PETG - PrusaOrange 3 (797.2%)</option>
<option value="">black - Prusament PETG - JetBlack 2 (0.0%)</option>
<option value="">white - TPU 95A - White 1 (631.0%)</option>
<option value="">dimgrey - TPU 98A - Gray 1 (510.4%)</option>
<option value="">black - PLA - Black 1 (0.0%)</option>
<option value="">black - Prusament PETG - JetBlack 1 (0.0%)</option>
<option value=""> - PLA - Orange 1 (0.0%)</option>
<option value=""> - Prusament PETG - PrusaOrange 1 (0.0%)</option>
<option value=""> - Prusament PETG - PrusaOrange 2 (0.0%)</option>
<option value="">red - PLA - Red 1 (0.0%)</option>
<option value="">white - PLA - White 1 (0.0%)</option>
<!--                     event: { change: onSelectSpoolItemForSidebar } ">-->
```

**Comment by d4rken** [comment]
It displays the weight in gram as %.

Think about it, we should either display just the gram, or gram+%, but not just the % as people use difference spool sizes (250g,750g,1kg,2kg) so knowing how many grams are left would be the most useful.

I guess changing the % to g would be the fix here?

**Comment by OllisGit** [comment]
Hi @d4rken,
it is implemented in RC4.

Please test and give me a feedback.

Thx, in advance
Olli

**Comment by d4rken** [comment]
:smile: Nice 


![Screenshot from 2020-07-29 06-21-42](https://user-images.githubusercontent.com/1439229/88756385-ced11d80-d163-11ea-8bbb-be51ca9beb30.png)
![Screenshot from 2020-07-29 06-21-36](https://user-images.githubusercontent.com/1439229/88756386-cf69b400-d163-11ea-87e3-9c7ebf892928.png)
