### ISSUE TITLE
QR Code Link ignores Reverse Proxy "proxy_set_header X-Script-Name"

### ISSUE THREAD

**Issue by lightmaster** [OllisGit/OctoPrint-SpoolManager#111]
My Octoprint server is behind a Reverse Proxy where the URL is in the form of `example.com/octoprint/`. SpoolManager's url is therefore: `example.com/octoprint/#tab_plugin_SpoolManager`. For the URL to print out the QR Code, SpoolManager is printing it out as just `example.com/plugin/SpoolManager`, dropping `/octoprint` from the url.

Just as a reference, the /octoprint is added by this in my nginx config:
```
proxy_set_header		X-Script-Name /octoprint;
```

**Comment by lightmaster** [comment]
Oddly enough, the QR Code itself contains the `/octoprint` part of the URL, just the link to get to the QR Code does not contain it.

**Comment by OllisGit** [comment]
Hi @lightmaster,

just: for my understanding
- the thumbnail-qr code is shown in your edit-dialog, right ?
- if you click on the thumbnail you receive a 404 (or page not found), because of the reverse-proxy
- if you patch the browser-url manuely you receive the full picture
- scanning the full picture includes the right url and the edit-spool page could be opened.

Short: the link from the thumbnail is broken, is this correct

**Comment by lightmaster** [comment]
See my screenshots in #112, the QR Code is not loaded in the edit dialog, but there is a link to the picture. Everything else, yes.

**Comment by VibroAxe** [comment]
@lightmaster if you go to example.com/octoprint/plugin/SpoolManager/generateQRCode/4 and scan the code, what url is it taking you to?

**Comment by lightmaster** [comment]
`example.com/octoprint/plugin/SpoolManager/selectSpoolByQRCode/4`

**Comment by VibroAxe** [comment]
@OllisGit this come from [L259-260](https://github.com/OllisGit/OctoPrint-SpoolManager/blob/4368360547a66bb0b05486a444b0fb001fed1c83/octoprint_SpoolManager/templates/SpoolManager_tab_dialogs.jinja2#L259`) in the dialogs jinja2. I'm not familiar enough with Jinja in Octoprint to know how to get the basepath for relative browsing

@lightmaster can you try installing from https://github.com/VibroAxe/OctoPrint-SpoolManager/archive/master.zip I think I have a solution

**Comment by lightmaster** [comment]
@VibroAxe Yea, gimme a little. Updating OctoPi to the new version right now.

**Comment by lightmaster** [comment]
@VibroAxe Yup, QR Code does work now with that fork. Annoyingly, there's still the other issue I submitted where SpoolManager and UI Customizer do not play nice together, so it brings up an edit dialog I can't scroll down to close on my phone.

**Comment by VibroAxe** [comment]
@OllisGit we can close this if you are happy to accept #115
