### ISSUE TITLE
Question about lenght

### ISSUE THREAD

**Issue by luco85** [OllisGit/OctoPrint-SpoolManager#113]
Hi! I not understand if fields total lenght and used lenght are obligatory or not thanks.

**Comment by VibroAxe** [comment]
Used length is filled automatically from the software odometer, Total length can be left blank, you will just end up with a -ve remaining length

![image](https://user-images.githubusercontent.com/1069212/105851239-b5a60e00-5fda-11eb-9653-f745919fa109.png)

Weight is key field for detecting "empty" spools

**Comment by luco85** [comment]
Ok! Thank you!
