### ISSUE TITLE
Cannot edit spools that have run out (>100%)

### ISSUE THREAD

**Issue by moarkaboom** [OllisGit/OctoPrint-SpoolManager#123]
I had a spool end during a print, but Spool Manager obviously had no way to understand, that I changed the spool for a new one during the print. The result is that my ended spool is now shown at 100.9%. I cant edit any material info in that spool now, only option is to set it to inactive.
![Screenshot 2021-02-09 154548](https://user-images.githubusercontent.com/78112271/107380144-e82d2c00-6aed-11eb-8095-a5fb59e1736f.png)
![Screenshot 2021-02-09 154503](https://user-images.githubusercontent.com/78112271/107380159-ea8f8600-6aed-11eb-9018-9554ee7aa3df.png)

**Comment by thirschbuechler** [comment]
if you can't see all the controls, maybe your user is not an admin

![image](https://user-images.githubusercontent.com/8376996/114582197-a8ff9080-9c80-11eb-94c1-a0b7a7c1ccf8.png)

**Comment by thirschbuechler** [comment]
you can set used weight to whatever you want

![image](https://user-images.githubusercontent.com/8376996/114582669-190e1680-9c81-11eb-8139-c62d18698e87.png)
