### ISSUE TITLE
Spool edition form problem [Bug]

### ISSUE THREAD

**Issue by courtpl** [OllisGit/OctoPrint-SpoolManager#124]
The bottom hidden part of spool form is not display after scroling
It is not possible to fill some fields.

see image:
![image](https://user-images.githubusercontent.com/43077828/107524885-91d7f000-6bb6-11eb-96ca-86d814153262.png)

**Comment by ThomxDK** [comment]
I have the same problem, but when I disable the "UI customizer" plugin the problem disappeared.

If I have the "UI customizer" plugin enabled ,and I zoom out in the browser to 50%, I can see all the fields, but it is only in one column.

Is it possible to add a scrollbar in edit menu?

**Comment by OllisGit** [comment]
duplicated, see #142
