### ISSUE TITLE
Can't set Length Remaining with Decimals

### ISSUE THREAD

**Issue by lightmaster** [OllisGit/OctoPrint-SpoolManager#128]
If you set the length remaining using decimals, ie 119,967.7mm, then it will not be saved when you hit the save button. Anything else you have edited will be saved, but length remaining/used will be blank for both. Admittedly keeping the length as a decimal mm is basically useless, but even still, it shouldn't cause it to be saved as blank.

**Comment by lightmaster** [comment]
Also, if you enter a number with a comma, it immediately considers that number to be 0, rather than parsing out the comma for the needed calculations. Displaying the numbers with commas would be really helpful, especially when you have 300000mm as a number.

**Comment by thirschbuechler** [comment]
bug confirmed. also, it seems the length is not synced with remaining mass, even though the density is provided
