### ISSUE TITLE
[Feature Request] Option to set length units

### ISSUE THREAD

**Issue by lightmaster** [OllisGit/OctoPrint-SpoolManager#129]
I'd like an option to for users to switch between mm and meters for filament length. I understand the reasoning behind using mm, since its the units used during extrusion, however meters is the units that filament is sold in (if its even advertised), and PrusaSlicer and Octoprint only tell you the meters required for a print, not the mm required. Being able to set it to meters would make it easier to quickly see if you have enough filament left for a particular print.

**Comment by abc2006** [comment]
+1 for me, too. Same thoughts as i just get used to octoprint. 
Great Plugin indeed!
