### ISSUE TITLE
[Feature request] Update default number of spools shown

### ISSUE THREAD

**Issue by shogun168** [OllisGit/OctoPrint-SpoolManager#135]
More of a usability issue but the first thing I do any time I open the Spools tab is go to the dropdown and click 'All' as I have 40 odd rolls or so and going between pages is just not efficient. It'd be great if you could default the selection to the last selected option. So if I hit 'All', it will always show 'All' any time I visit the spool page. Same goes for if I were to specify '25' or any other option in that dropdown. Thanks!

**Comment by OllisGit** [comment]
Hi,
in the latest release V1.4.0 I did some UI-Improvements.

Please test and give me a feedback.

Thx, in advance
Olli

**Comment by shogun168** [comment]
Thanks for the latest update. It's working great. Managed to reboot Octopi and after changing it previously, SpoolManager now defaults to 'All'. Awesome work :)
