### ISSUE TITLE
Support for Nightly Octoprint

### ISSUE THREAD

**Issue by uhlhosting** [OllisGit/OctoPrint-SpoolManager#138]
I see the plugin marked incompatible with latest release of nightly octoprint. Can you please mark this active if does not involve major changes.

**Comment by OllisGit** [comment]
Hi @uhlhosting,

I am not 100% sure what you mean, because I didn't use the nighly builds of Octoprint.
Maybe a screenshot helps or a link to OP-Doc/Releasenote.

BR
Olli
