### ISSUE TITLE
Feature Request: Checkbox to show/hide empty spools within the list

### ISSUE THREAD

**Issue by d4rken** [OllisGit/OctoPrint-SpoolManager#15]
I keep track of empty spools too.
This allows me to later lookup filaments I already used and re-order.
The field "purchased from" and "purchase data" that your plugin has is already awesome :ok_hand:.

I would find a checkbox that hides empty spools from the spool list very useful.

**Comment by OllisGit** [comment]
Hi @d4rken,
it is implemented in RC4.

Please test and give me a feedback.

Thx, in advance
Olli

**Comment by d4rken** [comment]
Works perfectly :heart:
