### ISSUE TITLE
Used length calculation doesn't match to slicer calculation

### ISSUE THREAD

**Issue by NguyenTanBao** [OllisGit/OctoPrint-SpoolManager#152]
Repro:
- Slice a model using PrusaSlicer
- Print
- Compare the used length calculation in this plugin vs PursaSlicer calculation (in the cost section inside gcode file)
- Two numbers do not match.

If I understand correctly, the used length calculation based on extrusion information in the gcode sent to the printer. So theoretically, for a successful print the number two numbers calculated by this plugin and by PrusaSlicer should match?

**Comment by OllisGit** [comment]
No feedback
