### ISSUE TITLE
Filament weight and length sync

### ISSUE THREAD

**Issue by Hesi-Re** [OllisGit/OctoPrint-SpoolManager#157]
It would be nice to sync filament weight and length so we can adjust just one of this if some print goes wrong. Now we must correct both.

It will also be helpful to show filament weight usage in filament tool (0) along with length

**Comment by OllisGit** [comment]
Hi @Hesi-Re ! 
The mentioned PR is now in the latest release!

Because I have a lot of issues related the weight calculation I close this issue to get a more "up to date overview" in the issue-tracker.
If you found an issue in the latest version feel free to raise a new issue!
