### ISSUE TITLE
SpoolManager gets broken by CalibrationCompanion

### ISSUE THREAD

**Issue by GylRon1** [OllisGit/OctoPrint-SpoolManager#159]
If CalibrationCompanion is installed and active, the add spool pop-up window is empty. I issued this too at the github page of CalibrationCompanion. Attached an empty window and the regular window.
![Add Spool empty screen](https://user-images.githubusercontent.com/84151858/118180250-9bcbf200-b436-11eb-8826-5f58dcc82c8f.png)
![Add Spool working screen](https://user-images.githubusercontent.com/84151858/118180272-9ff80f80-b436-11eb-865e-953400382777.png)

**Comment by tgkgate** [comment]
Can confirm,  window is broken with cal companion installed

**Comment by GylRon1** [comment]
iFrostizz is looking in to it. You can follow here:
https://github.com/iFrostizz/OctoPrint-CalibrationCompanion/issues/7#issuecomment-841132680

**Comment by akrilov** [comment]
Can confirm on my side as well. 
After installing calibration companion spool manager shows empty edit spool page.

**Comment by GylRon1** [comment]
Bug fixed by iFrostizz: https://github.com/iFrostizz/OctoPrint-CalibrationCompanion/releases
