### ISSUE TITLE
Feature request: Hide empty spools from the drop-down menu?

### ISSUE THREAD

**Issue by d4rken** [OllisGit/OctoPrint-SpoolManager#16]
The drop down menu is for "quick selection" before printing, imho.

What do you think about hiding empty spools from it?

**Comment by OllisGit** [comment]
Hi @d4rken,
it is implemented in RC4.

Please test and give me a feedback.

Thx, in advance
Olli

**Comment by d4rken** [comment]
Perfect :ok_hand:
