### ISSUE TITLE
Spools UI degraded after 1.4 update

### ISSUE THREAD

**Issue by jbienz** [OllisGit/OctoPrint-SpoolManager#165]
The Spools UI seems degraded after the 1.4 update. Lots of empty space on the sides and toward the bottom.

![image](https://user-images.githubusercontent.com/2062886/119411320-d6901e80-bcaf-11eb-8d9b-d52eee07dc9e.png)

**Comment by OllisGit** [comment]
Hi @jbienz,

what screen resolution do you use and what browser, what zoom-factor?
In the past some other plugins "collide" with spool-manager, please disable other plugins to see if it helps
E.g. I am using chrome and everything looks fine.
![image](https://user-images.githubusercontent.com/24205767/119414491-f34c4680-bcef-11eb-8af2-d73e03f5357e.png)

**Comment by achampion** [comment]
I'm using chrome and have a similar issue, they fields do not layout in 2 columns:
![image](https://user-images.githubusercontent.com/4431181/119422815-74431800-bcc7-11eb-80a9-f4aa2313f626.png)

**Comment by OllisGit** [comment]
Closed, duplicated! Tracked now here: #142 , because plugin author of "UI Customizer plugin" is involved.
