### ISSUE TITLE
Using UI Customizer - Spool Manager panel overlaps the one below 

### ISSUE THREAD

**Issue by Xiondewah** [OllisGit/OctoPrint-SpoolManager#171]
This is a different issue to the one where you couldn't add/see the content of the main add/edit window.

On the octoprint UI, if Spool Manager panel is displayed anywhere with other panels below, it's ui overlaps, making it un-readable:
![image](https://user-images.githubusercontent.com/50043329/119617556-e0be3400-bdf9-11eb-9ade-b422843fa2e6.png)

**Comment by OllisGit** [comment]
Duplicated, see #142, develeoper of UI Customizer is involved.
