### ISSUE TITLE
MultiMaterial records all use on the first filament

### ISSUE THREAD

**Issue by skarfacegc** [OllisGit/OctoPrint-SpoolManager#187]
Running spool manager 1.4.3
Printing through Mosaic Palette 2/mk3s+ via canvas -> octoprint 
Have octoprint setup for 4 extruders
Have 4 filaments loaded in spool manager

I'm not seeing any usage data recorded for anything but Spool0

Print was fine, I see this in print job history under tool measurement show-slicer settings
```
; DisplayLayerProgress_layerIndicatorProcessed = true
;    Ext 4 = 8589.94 mm
;    Ext 3 = 8708.16 mm
;    Ext 2 = 5271.16 mm
;    Ext 1 = 7249.56 mm
; END_LAYER_OBJECT z=15.000
; Dwell time remaining = -111.647316 s
; time estimate: pre = 22.328001 s, post = 116.647316 s
; path_width=0.4000
```

**Comment by OllisGit** [comment]
tracked here: #134
