### ISSUE TITLE
Sorting by remaining doesn't seem to work

### ISSUE THREAD

**Issue by speedysk1** [OllisGit/OctoPrint-SpoolManager#193]
I noticed that sorting by "Remaining" doesn't seem to work.  I don't know what it's sorting on specifically, but the Used % that I see on the screen certainly are not ordered correctly.  See attachment example
![Remaining_Sorting_not_working](https://user-images.githubusercontent.com/79531416/128025585-9154aba9-18fe-4313-b8aa-3679148de3dd.png)

**Comment by speedysk1** [comment]
@OllisGit Here you go.  Let me know if you need anything else.

[spoolmanager.zip](https://github.com/OllisGit/OctoPrint-SpoolManager/files/7392188/spoolmanager.zip)

**Comment by OllisGit** [comment]
Hi @speedysk1 ,
in the latest version the issue should be fixed.
Please test and give a feedback.

Thx in advance
Olli
