### ISSUE TITLE
unable to set a bought on: date

### ISSUE THREAD

**Issue by themoonisacheese** [OllisGit/OctoPrint-SpoolManager#205]
when   creating a new spool or editing an existing one, if a bought on: date is specified, the changes won't stick or the new spool won't get registered at all. this seems to happen whether the date is in the past or the future.

**Comment by lorez42** [comment]
I've had similar problems with the current firefox (93.0).  When I select a date for the purchased, for example, say 10/25/2021, it actually fills in 1.36.2021, then throws the datetime format error in the log when trying to save.

**Comment by oerkel47** [comment]
Can confirm problems. The first and last used dropdown list also produce a broken time setting. The moment you click on a date it inserts the bugged date into the field. If you type in a date by hand it also parses it to the incorrect date.

![grafik](https://user-images.githubusercontent.com/57231822/139947501-87d90caa-ed55-4021-a8be-cdd5bc7fc89d.png)
![grafik](https://user-images.githubusercontent.com/57231822/139948051-5072a521-7500-408e-96d2-bc28d5fdee3a.png)
![grafik](https://user-images.githubusercontent.com/57231822/139948117-0f0d0d6d-a8c3-4d08-a0bd-4bc021711689.png)

**Comment by OllisGit** [comment]
Hi @oerkel47,
thanks for providing the screenshots. You and also @themoonisacheese are using Firefox. Is this issue also reproducible with a chrome browser.
I played around with FireFox, different browser locals, but I was not able to reproduce the error.

It looks like that the datetimepicker is also not supported any more and I couldn't find an related issue in tracker.
https://github.com/xdan/datetimepicker

**Comment by oerkel47** [comment]
Thanks for looking into it.

Same problem in chrome and on my phones firefox.

**Comment by OllisGit** [comment]
hmmm...okay, I think I will switch to the html-standard picker: https://www.w3schools.com/tags/att_input_type_datetime-local.asp
....but the user needs a "modern" browser.

**Comment by themoonisacheese** [comment]
chrome has had support for this for 9 years, but firefox only recently added datetime-local in version 93 this year. maybe the more recent versions that support the standard don't work well with the previous datetime picker?

**Comment by oerkel47** [comment]
> 
> 
> hmmm...okay, I think I will switch to the html-standard picker: https://www.w3schools.com/tags/att_input_type_datetime-local.asp ....but the user needs a "modern" browser.

As long as the unsupported browsers can still use the manual input that wouldn't be too critical imo.

**Comment by flexik** [comment]
Can confirm that this happens both in Chrome and Firefox for me. Not sure what is the cause as I should have English locale set.

**Comment by OllisGit** [comment]
Hi, 
in the latest release I change the date/time-picker to the browser-native implementation. I think this is the best solution...hopefully ;-)

Please test and give a feedback.

Thx in advance,
Olli

**Comment by oerkel47** [comment]
The datepicker seems to be working just fine now - thank you.

**Comment by flexik** [comment]
In the latest version it works great. Thanks a lot!
