### ISSUE TITLE
Define IP/URL to use for QR codes

### ISSUE THREAD

**Issue by sym0nd0** [OllisGit/OctoPrint-SpoolManager#207]
This could be user error or a very niche issue, if so please tell me to stop being stupid. 

If I open the spool dialogue on my laptop, which uses mDNS, the QR code generates a URL of http://octopi.local. Sadly, Android, which I'm mostly likely to use to scan QR codes, doesn't allow for zeroconf to work in a browser, so I hit on a 403 error.

Where as, if I open the spool dialogue from Chrome on my Android the QR code generates a URL of http://192.168.X.XX.

Is it possible to define the URL that the QR code is generated from, so that no matter the device used it will always default to one that works - in my case, local IP?

**Comment by OllisGit** [comment]
fyi, is in the next release look like this:
![image](https://user-images.githubusercontent.com/24205767/154432138-18b1d34b-addb-4c0c-a685-053d1599f547.png)

**Comment by sym0nd0** [comment]
> fyi, is in the next release look like this:
> ![image](https://user-images.githubusercontent.com/24205767/154432138-18b1d34b-addb-4c0c-a685-053d1599f547.png)
> 

Superstar, thank you!

**Comment by OllisGit** [comment]
Hi @sym0nd0,

in the latest  RC-Verison  1.7.0rc1 I changed a lot of stuff, maybe this issue is also solved.
Please test and give feedback

Thx, in advance
Olli

**Comment by OllisGit** [comment]
Hi @sym0nd0,

the sample qr-image in the plugin settings shows the current saved settings. 
So, if you enable and change the ip-address it is not directly reflected to the image (will be change in the next release). You need to press save and reopen the settings to the the ip also in the sample image.

And your attached full qr-image shows the correct ip, like entered in the plugin settings: ```http://192.168.1.71```

Please try again.

**Comment by OllisGit** [comment]
Hi, 
new Version 1.7.0 is released and the qr-code image is now updating after the url-prefix is changed and not after save.

Please test and give feedback.

Thx, in advance
Olli

**Comment by sym0nd0** [comment]
Hi @OllisGit,
As always, thanks for the update!

I've tested with V1.7.0 and updating the URL/IP works perfectly and is reflected in real-time. 🕺🏼

Only thing that doesn't appear to update is the spool name on the large QR-image. For example:

![image](https://user-images.githubusercontent.com/55590428/159114457-050a6e6d-75df-496c-b159-6869d9ae0153.png)
From my list of spools, I click on Jiawill PLA Red #ff0000.

![image](https://user-images.githubusercontent.com/55590428/159114500-d5fb63be-365f-491f-b7c0-37fb0756ff50.png)
Which opens the correct spool.

![image](https://user-images.githubusercontent.com/55590428/159114520-8239f399-e49c-4060-a69a-7fe1daa9e82f.png)
That opens the large QR-image for the correct spool (DB ID, URL and QR code), but the Spoolname is wrong (no matter the spool selected, it always displays the Spoolname as being PRUSAMENT Black PETG, which is DB ID 2).

It's definitely not a showstopper, as it's purely cosmetic, but figured you'd want to know.

Also, can you please include another method of being able to buy you a coffee? I don't have Paypal.

Thanks again.

**Comment by chrda81** [comment]
I'm using the Spool Manager v1.7.0 in Octoprint-Docker and can confirm, that the same spoolname is shown for all of my different spools as well. And when I try to scan the QR Code, that error message is shown in the browser:

`{"error":"A conflict happened while processing the request. The resource might have been modified while the request was being processed."}`

The url _http://192.168.178.68:8090/plugin/SpoolManager/selectSpoolByQRCode/4_ is shown in the address bar and the docker log says that the spool 4 was selected, but only the error above is visible in the browser.
