### ISSUE TITLE
Change spool dialog doesnt match selectable options

### ISSUE THREAD

**Issue by elminster** [OllisGit/OctoPrint-SpoolManager#211]
Minor bug but when you change spool mid-print the dialogue box gives the wrong option names.

'You are changing a spool while printing. SpoolManager will commit the usage so far to the previous spool, unless you wish otherwise ....'

You are asked to click either 'Ok' or 'Abort'

but the dialog box buttons are labelled 'cancel and 'ok'

![image](https://user-images.githubusercontent.com/63932/138920369-f87c459f-f338-4195-8862-f781bfb275e2.png)

**Comment by eacxx** [comment]
![image](https://user-images.githubusercontent.com/88005990/147140713-4d18a8ee-2f63-4bf2-98de-481329c1f3ba.png)
Firefox 95 on macOS Big Sur.

**Comment by OllisGit** [comment]
fyi: Button-Text is changed
