### ISSUE TITLE
Move from "Filament Manager"

### ISSUE THREAD

**Issue by WimVDK** [OllisGit/OctoPrint-SpoolManager#212]
Just found this plugin which seems to be the successor to your "Filament Manager" that you took over from someone else a while ago. I swapped to that one as my android app i was using to manage spools didn't sync my spools back. I have exported my spools from there but i'm having problems with this plugin.

I found out where to add spools, but in order to add spools i need to add a vendor. The problem is i can't find out wher to add a vendor nor can i find out where/how to import my "Filament Manager" profiles & spools.

I'm getting a bit overwhelmed atm as i'm seeing "Printer Display" in the bottom left, a warning about "filament tracking is possible in the top right" and something about layer height etc not being detected. From what i get so far the "Printer display" is the same as what i'm seeing under "printer notifications". I don't need a M117 notification about the % or layer as i can see the % in the progress bar of my CR-10 Max.

Nor is the documentation any help atm,

i'd be very grateful of any and all assistance.

**Comment by OllisGit** [comment]
Hi @WimVDK,
well documentation is always helpful ;-) ...Unfortunately it also took a lot of effort to create.
It is on my list (a starting point is a FAQ in the Wiki)..or feel free to provide a documentation which I could include here ;-)

But you are mixing multiple plugins . Each plugin has multiple responsibilities and some plugins interact with each other. But it is also possible to use each plugin individualy.

E.g. you are using DisplayLayerProgress which include theses features:
- "Printer-Display" in lower  corner. Every M117 which was sent by OP is displayed also in the Web-Browser. Can be deactivated via Plugin-Settings
![image](https://user-images.githubusercontent.com/24205767/140204166-cdc47258-1697-413c-bafc-26d2c39635e0.png)
- Extract Layer-Informations from the GCode during the upload of the file. If the gcode doesn't include special layer-comments the plugin could not extract this information and shows a warning (could also be disabled)

PrintJobHistory-Plugin
- This plugin captures each printjob-data and stores the result in a database. Beside the "out-of-the-box" information like start/end-time it captures also the layer-informations provided by the DLP-Plugin (if installed)
- And it could also capture the filament usage. But to do this, it needs a plugin that could capture the filament. The popup is a hint to select a tracking plugin 
![image](https://user-images.githubusercontent.com/24205767/140210187-f01b61e8-5f2b-444d-8c58-c6dff71a4133.png)
![image](https://user-images.githubusercontent.com/24205767/140210965-58aebd6c-d4ac-4208-b095-3129e068a3d6.png)

 Switching from FilamentManager to SpoolManager
- The easiest way is to install both plugins and to export the FM-Data via the SpoolManager-Plugin. This way all data is exported in a format that could be easily manipulated via Excel (or Texteditor) and reimported into SpoolManager
 ![image](https://user-images.githubusercontent.com/24205767/140215594-9718b06d-fa30-4c9e-b52c-f0821d2ed30b.png)

In the SpoolEdit-Dialog enter your spool vendor name into the field, hit enter and press save. After that, you can reuse the vendor name in the next spool.

Profiles like in FM is not supported in SpoolManager.


I hope I answered all of your questions...if so, please close the issue.

**Comment by WimVDK** [comment]
One thing at a time, lets start by getting SpoolManager to work. I thought i might be mixing things but they 3 of those got installed cause SM recommended PJH and PJH recommended DLP in one way or another. I thought i had to export the csv from FM THROUGH FM, apparently not. So i managed export its db though SM, didn't see the sample csv so just straight up loaded it in SM but the "upload & import" is spinning. Could it be because there's a print going on?

**Comment by OllisGit** [comment]
fyi: In the next release the import function is only available if the printer is not busy.

**Comment by OllisGit** [comment]
Hi,
in the latest version the issue should be fixed. 
Please test and give a feedback.

Thx in advance
Olli
