### ISSUE TITLE
Sort sidebar plugin "Select Spool"

### ISSUE THREAD

**Issue by ShagoY** [OllisGit/OctoPrint-SpoolManager#213]
Hello,
I would like to be able to sort the sidebar dropdown menu.

Currently it sorts by "last used", if we could at least sort by name and/or materials, I'd think that would be great!
![image](https://user-images.githubusercontent.com/25367500/140649886-71f1bbc7-ce2a-47fa-bad5-280e85fce3ac.png)

**Comment by OllisGit** [comment]
Hi @ShagoY,

good idea. 
The current idea looks like this and will be available in the next version.
![image](https://user-images.githubusercontent.com/24205767/140662926-e7482979-9162-41b0-ba59-2fa6c8a1c4b7.png)

**Comment by OllisGit** [comment]
Hi @ShagoY ,
in the latest version the feature is implemented. 
Please test and give a feedback.

Thx in advance
Olli
