### ISSUE TITLE
Can't figure out why (missing metadata)

### ISSUE THREAD

**Issue by Filmman586** [OllisGit/OctoPrint-SpoolManager#214]
I'm getting this message, but I dont know why...Any suggestions?

![Screenshot 2021-11-09 061751](https://user-images.githubusercontent.com/83276762/140915363-c6562c82-dfcf-4570-b86f-0c8f63d0c0e7.png)

Lou

**Comment by MrRexRuthless** [comment]
I just started receiving this as well.  Started a print this morning from Octodash, i believe and it failed.  Went to restart again from the OctoPrint Web Interface and received this error.  Have restarted PI.

**Comment by OllisGit** [comment]
Hi @Filmman586,

to calculate the needed weight the plugins needs some data from OP. The data is stored in a file called ```.metadata.json``` and is located in the upload folder (look for analysis/filament). 
```
        "analysis": {
            "printingArea": {
                "maxX": 127.881,
                "maxY": 95.506,
                "maxZ": 10.9,
                "minX": 88.081,
                "minY": 42.554,
                "minZ": 0.3
            },
            "dimensions": {
                "depth": 52.952,
                "height": 10.6,
                "width": 39.8
            },
            "estimatedPrintTime": 2754.571579330689,
            "filament": {
                "tool0": {
                    "length": 2016.75497,
                    "volume": 0.0
                }
            }
        }
``` 
If this meta data is not available the popup appears (or you didn't select a spool for tool 0).
Please check which option do you select in the features-section of the settings.
![image](https://user-images.githubusercontent.com/24205767/141701922-d1173575-01b8-4cee-b04c-39c0ee83116a.png)

**Comment by MrRexRuthless** [comment]
> I just started receiving this as well.  Started a print this morning from Octodash, i believe and it failed.  Went to restart again from the OctoPrint Web Interface and received this error.  Have restarted PI.

Mine seemed to go away by itself.  I will update if I see it repeat.

**Comment by FoxRomeo** [comment]
I had the same issue.
With the data here I could find out more data and the cause (in my case).
Hardware: RPi3

It happened in my case only with large prints that have no estimatedPrintTime when the print starts. Then I receive the "no spool selected" dialog.
As soon as I installed other plugins that make faster estimate calculations, then this dialog disapears.

Therefor it seems to be no error in this plugin, more like missing required data that leads to a (maybe missleading) dialog.

If you encounter such beavior check for the estimate time, and try the plugins OctoPrint-MetadataPreprocessor and OctoPrint-PrintTimeGenius could help you in case (it did in mine).
