### ISSUE TITLE
Filament usage amount is wrong when print is paused

### ISSUE THREAD

**Issue by hvraven** [OllisGit/OctoPrint-SpoolManager#217]
When a print is paused mid print (in my case using M600 to insert a part into the printed piece) the plugin counts the filament usage wrong. I did not change the spool during the pause, maybe when changing the spool this does not happen.

Based on the amounts I've seen it appears that on pause the filament used so far is subtracted from the spool and in the end the whole amount is subtracted again.

I looked a bit into the code and it appears that the filament counter is only reset on the start of the print. There is a reset the commit function, but it is commented out. I don't see why, for me it would make sense to reset there, but I am also lacking an overview of the full code base.
 https://github.com/OllisGit/OctoPrint-SpoolManager/blob/45bdb5273b1892c46373ef4770c24be8ebf01e81/octoprint_SpoolManager/__init__.py#L458

**Comment by OllisGit** [comment]
Hi @hvraven,
in the latest version the issue should be fixed.
Please test and give a feedback.

Thx in advance
Olli
