### ISSUE TITLE
[Feature request] Auto select spool based on file prefix

### ISSUE THREAD

**Issue by andritolion** [OllisGit/OctoPrint-SpoolManager#220]
I have my Gcode files all prefixed with my printer prefix in Cura with a plugin that adds an abbreviated filament name. It would be nice if Filament Manager could auto select the filament spool by letting us define regex to determine the filament spool in use, so we only need to set the filament spool in one place (and maybe only add a filament color prefix) when slicing. For example, if the Gcode file was named like CE3_OPLA_RED_3DBenchy.gcode, Filament Manager could select my red spool of Overture PLA.

**Comment by OllisGit** [comment]
Hi @andritolion,

I see some "challenges":
- In your example there is no separation between Spool and Filename. Should be ``` CE3_OPLA_RED-3DBenchy.gcode``` --> ```(.*)-(.*)```. But then you need to make sure that the filename should not include a minus.
- Any idea how a MultiColor-Print could handled multiple spool-selection?

There are already some requests about spool-selection via gcode comments, will this help you as well?
