### ISSUE TITLE
Plugin not working, because of Database issues. Check Plugin-Settings!

### ISSUE THREAD

**Issue by d4rken** [OllisGit/OctoPrint-SpoolManager#223]
![Screenshot from 2022-01-13 12-17-29](https://user-images.githubusercontent.com/1439229/149320681-92db9749-57b1-40a2-bf3e-d190e2ac1c3b.png)

Octoprint Version 1.7.2
SpoolManager Version: 1.6.0

[octoprint-spoolmanager.log](https://github.com/OllisGit/OctoPrint-SpoolManager/files/7862273/octoprint-spoolmanager.log)
[spoolmanager.zip](https://github.com/OllisGit/OctoPrint-SpoolManager/files/7862279/spoolmanager.zip)

As far as I can tell, the plugin does work though and tracks consumed filament.

**Comment by OllisGit** [comment]
Really strange...from implementation perspective it is not possible:
![image](https://user-images.githubusercontent.com/24205767/149376013-6cb24c61-d177-478d-933a-ba0b805ec300.png)
There is only one boolean flag that decide to show the error-sentence OR the table-data and NOT both.

Do you have other plugins installed that "improves" the UI? 
In your log I missed the starting phase, so I can't see what plugins are installed.

**Comment by d4rken** [comment]
* Cura Thumbnails (1.0.1) 
* Dashboard (1.19.6) 
* DisplayLayerProgress Plugin (1.27.2)
* FileManager (0.1.6)
* Firmware Updater (1.13.0)
* Navbar Temperature Plugin (0.14) 
* Octolapse (0.4.1) 
* Preheat Button (0.8.0) 
* PrintJobHistory (1.15.2) 
* PrintTimeGenius Plugin (2.2.8) 
* Resource Monitor (0.3.6) 
* Slicer Thumbnails (1.0.0)
* SpoolManager Plugin (1.6.0) 
* Tab Order (0.5.12) 
* Themeify (1.2.2)

**Comment by d4rken** [comment]
Seems to be caused by Themeify:
https://github.com/birkbjo/OctoPrint-Themeify

**Comment by OllisGit** [comment]
Hi @d4rken,

I installed the plugin, but I am not able to reproduce the issue. 
So, when you disable "Themeify" then the DB message is gone, right?

What settings do you use?
![image](https://user-images.githubusercontent.com/24205767/149630890-bdca78ae-6186-4ab4-96d4-4fa6f03c4c03.png)

![image](https://user-images.githubusercontent.com/24205767/149630878-94ad9883-0954-4615-bea9-fcd5b99ffb09.png)

**Comment by d4rken** [comment]
I played a bit more and when I disable "customizations" and reload the page, it's also fixed.

![Screenshot from 2022-01-15 20-03-09](https://user-images.githubusercontent.com/1439229/149634593-67cbdbc3-6c05-4207-a0d5-0f3d9be2248f.png)
![Screenshot from 2022-01-15 20-02-39](https://user-images.githubusercontent.com/1439229/149634595-d4dc7272-9abc-497b-9cee-a8c34aa482f5.png)
![Screenshot from 2022-01-15 20-00-10](https://user-images.githubusercontent.com/1439229/149634596-5cb270c8-2448-4074-9a3c-20aab2b8cbfd.png)

**Comment by OllisGit** [comment]
Thx, for the screenshot! Now I was able to identify the issue, it is related to ```.row-fluid```.

I will fix this in the next release. In the meantime you need to remove this entry...or ignore the message (like you do in the past).

BR
Olli

**Comment by d4rken** [comment]
Thank you so much for all your contributions to the 3D printing community :heart:.

**Comment by OllisGit** [comment]
Hi @d4rken,

the new bugfix release 1.6.1 is out.

Please test and give feedback.
Thx, in advance
Olli

**Comment by d4rken** [comment]
Fixed :+1:
