### ISSUE TITLE
"Hide inactive spools" toggle doesn't work

### ISSUE THREAD

**Issue by MarloSM** [OllisGit/OctoPrint-SpoolManager#228]
Hi, great work on the plugin!

Just noticed recently that the "Hide inactive spools" toggle acts as untoggled if the page is refreshed even though it's toggled. Seems like the page defaults this setting to untoggled, rather than taking the value of the variable? Haven't dived deep, just guessing.

**After refresh, before re toggle**
![image](https://user-images.githubusercontent.com/22463469/150744706-577d2ded-794f-40a8-aaae-6fa0b5de645b.png)

**After refresh, after re toggle**
![image](https://user-images.githubusercontent.com/22463469/150744742-d5b5b5f5-f7d0-495e-8c65-b16a7ef534ef.png)

**Comment by OllisGit** [comment]
Side note to myself: 
- total spool count in tab not refreshed
- output spool-count to selection-dialog

**Comment by MarloSM** [comment]
I had a look today on Google Chrome and Firefox and this issue is still around, sorry.

There's an added UI issue where if you click on the words "Hide inactive spools", it toggles "Hid empty spools". As if the active area for the first option is bigger. Only clicking on the tickbox for "Hide inactive spools" works.

**Comment by OllisGit** [comment]
Hi @MarloSM, 
new Version 1.7.0 is released and fix the issue

Please test and give feedback.

Thx, in advance
Olli

**Comment by MarloSM** [comment]
Hi @OllisGit. Working great now, thanks.
