### ISSUE TITLE
[Feature request] Spool ID 

### ISSUE THREAD

**Issue by EvilBlood** [OllisGit/OctoPrint-SpoolManager#229]
Moin,
ich wollte mal fragen ob es möglich wäre in der Tabellen Ansicht und in der der Auswahl die Spool ID mit anzuzeigen (Nummer aus QR Code Link). 
Vielleicht wäre es auch möglich bei dem QR Code Bild als kleiner Text unterhalb die ID mit anzuzeigen das man bei vielen ähnlichen spulen direkt die ID zum Identifizieren hat.

Mit freundlichen Grüßen

Daniel

**Comment by OllisGit** [comment]
Hi, 
new Version 1.7.0 is released.

Please test and give feedback.

Thx, in advance
Olli

**Comment by EvilBlood** [comment]
Moin Olli,

schaut sehr gut aus 👍, vielen dank für die Erweiterung.
