### ISSUE TITLE
[BUG] Broken CSS declaration

### ISSUE THREAD

**Issue by LazeMSS** [OllisGit/OctoPrint-SpoolManager#230]
The ".dropdown-menu" css should be removed ASAP.

https://github.com/OllisGit/OctoPrint-SpoolManager/blob/02e6231ff476677a46a202455b20531280c717fd/octoprint_SpoolManager/static/css/SpoolManager.css#L94

It's a rewrite of a standard bootstrap class name and therefore affects all dropdown menus.

Try an use the CSS selectors so they only affect your own plugins - ie:
`#tab_plugin_SpoolManager .dropdown-menu`

**Comment by OllisGit** [comment]
Hi @LazeMSS,

I removed the  css-class, should be working now.

Please test and give feedback.
Olli

**Comment by LazeMSS** [comment]
Fixed
