### ISSUE TITLE
SpoolManager not tracking usage

### ISSUE THREAD

**Issue by jet8300** [OllisGit/OctoPrint-SpoolManager#231]
SpoolManager is not working correctly for me. It is not tracking filament usage even when a spool is selected. If I attempt to start a print with no spool selected, I also do not get a prompt telling me to select one, even though I have the options selected to verify a spool is selected.

I am running the following environment;

- OctoPrint 1.7.3
- Python 3.7.3
- OctoPi 0.18.0

Enabled 3rd party plugins:

- Bed Visualizer 1.1.1
- OctoKlipper 0.3.9.4
- PrintJobHistory 1.16.0
- Slicer Thumbnails 1.0.0
- SpoolManager Plugin 1.6.0

I have attempted uninstalling SpoolManager and fully reinstalling it. I even created a new spool rather than importing my old database.

Any help would be greatly appreciated. I love this plugin!

**Comment by OllisGit** [comment]
Hi @jet8300,

interesting you love this plugin, but it is not working for you...my feelings would be hate and not love ;-)  

Please attach the octoprint.log maybe there is an error documented.

**Comment by jet8300** [comment]
Well, it was working perfectly until recently. I think that the issue is actually more something to do with superslicer and octoprint, and not your plugin, the more I look into this. 
[octoprint.log](https://github.com/OllisGit/OctoPrint-SpoolManager/files/8007107/octoprint.log)

Octoprint doesn't appear to be getting the filament usage data from the gcode generated by superslicer.

**Comment by jet8300** [comment]
So after more digging, it looks like Octoprint is getting the data from the gcode; it's listing it in the metadata. Not sure if that helps.

**Comment by OllisGit** [comment]
Hi @jet8300,

the real extruded data (length) is captured during the print, by reading each  gcode line (e.g. G1 ... E1000).

Activate the "Extrusion debugging" in the plugin settings, then you can see during the print if the extrusion is captured.
![image](https://user-images.githubusercontent.com/24205767/154120098-25c6319e-ff6e-4a65-b0f9-eaabf307c423.png)
![image](https://user-images.githubusercontent.com/24205767/154120222-bfccff7e-d42b-4401-a130-8ad41dff24a2.png)

Maybe it is related to your used slicer, so please attach the gcode as well, so I can try to reproduce the issue in my environment.

**Comment by jet8300** [comment]
Here is an example gcode. I am using the latest version of superslicer.

[Bridge calibration_gcode.txt](https://github.com/OllisGit/OctoPrint-SpoolManager/files/8097915/Bridge.calibration_gcode.txt)

I ran this print and here is the octoprint log:
[octoprint.log](https://github.com/OllisGit/OctoPrint-SpoolManager/files/8097925/octoprint.log)

I don't see any extrusion data in there, but I did enable debugging as you asked.

**Comment by OllisGit** [comment]
Hi @jet8300,
I analysed your provided GCode and it looks like that the movement of extruder motor is interpreted as absolut positioning. But in the gcode-file all E-Values looks like relative values.

![image](https://user-images.githubusercontent.com/24205767/159063910-8c405200-2c8e-4960-bbaf-2dc74f68c1cd.png)

The default behaviour from OctoPrint and my plugin is, that if no special gcode for movement-mode is provided, each value is interpreted as absolut.
OP is not able to calculate the total length. 

From your gcode:
![image](https://user-images.githubusercontent.com/24205767/159065268-5c68faae-6957-4db7-8e92-68dd818ac6a7.png)

From OP (```.metadata.json```)
![image](https://user-images.githubusercontent.com/24205767/159065468-368afd72-381b-4d37-8383-e0b8e4cec272.png)

My Assumption is, that your printer acts the other way around. No special command, then it is relative.

G-Code for movement-mode are:
- G90 absolute
- G91 relative
- M82 absoute extruder
- M83 relative extruder

Try to add a ```M83``` command in your gode.
