### ISSUE TITLE
Switch to release candidate and dev build for external database version!?

### ISSUE THREAD

**Issue by Doprintityourself** [OllisGit/OctoPrint-SpoolManager#234]
Changed to the release and dev version in the upgrade section, but do not get any higher version that 1.6.1

Shouldn't I get the  1.7.x beta with the external database already available?

Thanks in advance

**Comment by OllisGit** [comment]
Nope!
Take a look into the release page. 
https://github.com/OllisGit/OctoPrint-SpoolManager/releases
The highest release is still 1.6.1.

At the moment there is no dev-release with external database. Here in github is branch "externalDatabase" but this is still "work in progress".

I am jumping between my plugins and currently I am preparing a new release of PrintJobHistory, after that SpoolManager is next, maybe with external DB.
