### ISSUE TITLE
Warning of insufficient material before print is started?

### ISSUE THREAD

**Issue by Spacemarine2018** [OllisGit/OctoPrint-SpoolManager#24]
I'm running a small print farm and I want to avoid changing a spool in the middle of a print. Can SpoolManager give a warning, if the spool has insufficient material left?

Ideally, I'm just running one job after the other until SpoolManager gives a clear warning (or even blocks the START button) until I confirm that the spool is exchanged, so the system becomes idiot-proof.

I'm currently only printing one material, so a button "new spool has ben inserted" would be enough for normal operation.

**Comment by OllisGit** [comment]
Hi @Spacemarine2018,
please test newest Version 1.0.0 and give feedback.

Thx, in advance
Olli

**Comment by manolitto** [comment]
Is there also a chance to automatically pause or abort the print when started via API and there is not enough filament left?
I usually start my print jobs directly from SuperSlic3r with "autostart" option. Prusa Mini with current firmware is currently not able to pause when printing via OctoPrint and running out of material.
This would be a cool feature and would make it fool proof via API either.
