### ISSUE TITLE
Add drop down for price to change to other currencies.

### ISSUE THREAD

**Issue by bodyboarder2528** [OllisGit/OctoPrint-SpoolManager#240]
I am from Australia and would like to have the Australian dollar as a option instead of the euro please.

**Comment by OllisGit** [comment]
Hi @bodyboarder2528,

just change the symbol in the plugin settings:
![image](https://user-images.githubusercontent.com/24205767/153962814-637821b2-33f0-4796-862f-0a75c4646c41.png)

**Comment by bodyboarder2528** [comment]
Oh missed that cheers
