### ISSUE TITLE
Feature Request: Support Filament Finish ( Matte, Galaxy/ Speckle, Silk, Metallic )

### ISSUE THREAD

**Issue by jDavidnet** [OllisGit/OctoPrint-SpoolManager#242]
It would be nice to be able to filter your filaments by Finish.  I'd like to be able to look at my set of Matte filaments to print a mini, or silk or galaxy filaments to print a decoration or toy.

**Comment by OllisGit** [comment]
This could be handled with the planed feature: "labels"
![image](https://user-images.githubusercontent.com/24205767/154372010-9e31b355-fa7e-4aed-9f24-c42a4b287a6a.png)

**Comment by jDavidnet** [comment]
Can you add this to the backlog?
