### ISSUE TITLE
Support external py script OR use of Adafruit EMC2010 to control enclosure temps on a per-spool basis

### ISSUE THREAD

**Issue by JeremyLaurenson** [OllisGit/OctoPrint-SpoolManager#244]
Hey folks,

I have hooked up an [Adafruit 2101 board](https://learn.adafruit.com/emc2101-fan-controller-and-temperature-sensor/overview) to a PWM fan controlling airflow in my enclosure.
The basics are pretty simple, a Look Up Table (LUT) can be sent to the 2101 via python in order to set the desired fan speeds by temperature.
So, if we want the desired enclosure for PLA to be 20 degrees c, we may set up a table that says:
If enclosure temp is at 20 degrees, fan is at 20% speed
If enclosure temp is at or above above 22 degrees, fan is at 40% speed
If enclosure temp is at or above 24 degrees, fan is at 60% speed
If enclosure temp is at or above 25 degrees, fan is at 100% speed

This would be done using python:

```

import board
from adafruit_emc2101.emc2101_lut import EMC2101_LUT as EMC2101
i2c = board.I2C()  # uses board.SCL and board.SDA
FAN_MAX_RPM = 1700
emc = EMC2101(i2c)
emc.lut[20] = 20
emc.lut[22] = 40
emc.lut[24] = 60
emc.lut[26] = 100
emc.lut_enabled = True


```
Crazy simple. 

I would like to do this using filament manager so each filament has a fan setting for it's type that can be sent to the fan when that filament is selected or begins to print.

This could be a simple script thats run, or built into the plugin. I am happy to dig around and help.

Thoughts?

**Comment by OllisGit** [comment]
Looks similar with this request: https://github.com/OllisGit/OctoPrint-SpoolManager/issues/154
Each spool has it's own gcode.

**Comment by JeremyLaurenson** [comment]
Folks are going to want to set this way before printing starts to allow the enclosures to stabilize. Im going to do this work in the enclosure plugin.
