### ISSUE TITLE
Material weight only displays whole numbers with Spool Manager

### ISSUE THREAD

**Issue by net147** [OllisGit/OctoPrint-SpoolManager#245]
The following is displayed by the Cost Estimation plugin:
Tool 0: 0.64m / 1.00g

I am using it with Spool Manager. The spool has the following settings:
Density: 1.27 g/cm^3
Diameter: 1.75 mm

It should be 1.89g instead of 1.00g.

If I change density from 1.27 to 2.00 then Cost Estimation plugin displays;
Tool: 0: 0.64 m / 3.00g

**Comment by OllisGit** [comment]
Hi @net147,

in the latest  RC-Verison  1.7.0rc1 I changed a lot of stuff, maybe this issue is also solved.
Please test and give feedback

Thx, in advance
Olli

**Comment by OllisGit** [comment]
Hi, 
new Version 1.7.0 is released.

Please test and give feedback.

Thx, in advance
Olli

**Comment by Nemoron** [comment]
I got the issue as well. I have the your SpoolManager and FilamentManager plugins installed. FilamentManager calculates everything correctly, but SpoolManager ist off.

Filament:
Density 1,24g/cm³
Diameter 1,75mm ± 0,03mm

output: 
Filament (Tool 0): 1.02m / 3.04g
Tool 0: 1.02m / 4.53g

**Comment by Nemoron** [comment]
CostEstimation shows the same price for either plugin selected.
