### ISSUE TITLE
Support for MQTT

### ISSUE THREAD

**Issue by notenoughtech** [OllisGit/OctoPrint-SpoolManager#246]
Hi, 

I wonder if it would be possible to add the MQTT option to share the writes to the database? It would enable logging externally without reading the DB or hosting it on another server. 

Thanks

**Comment by OllisGit** [comment]
Hi @notenoughtech,

in combination with this plugin [MQTT](https://github.com/OctoPrint/OctoPrint-MQTT) and the checkbox "Unclassified events" , it should be easy to implement. I just need to fire an event.

These are the events that could be helpful:

- updateSelectedSpoolWeight
- selectedSpool
- removeSelection
- updatedSpoolData
- addedSpool
- deletedSpool

Did I miss something?

**Comment by notenoughtech** [comment]
I couldn't see it on the list of events so I skipped it.
I wrote a small python scraper last night that hooks up directly to the SQL
file and sends the updates.

I'll think about the event approach now as well. I want to use some NFC to
inject the spools to the database. Are you anticipating any issues caused
by duplicating DB entries?

**Comment by OllisGit** [comment]
Hi @notenoughtech,

in the latest RC-Version 1.7.0rc1 I implemented the event-mechanism.
Please test and give feedback

If you update/create the database by your own, it could go wrong and the plugin stops working ;-)

Thx, in advance
Olli

**Comment by notenoughtech** [comment]
I'll live my life dangerously :)
I'll check it out thanks for the heads up

**Comment by OllisGit** [comment]
Hi @notenoughtech,
currently the selected spools were stored in the local octoprint plugin-settings (see ```<op>/config.yml```
![image](https://user-images.githubusercontent.com/24205767/159023895-027bf15d-d9cd-452f-89a1-af7042031696.png)
These information will be move into the database (feature "external db")...will take some time.

**Comment by OllisGit** [comment]
Hi @notenoughtech,
new Version 1.7.0 is released and include the MQTT feature.

Please test and give feedback.

Thx, in advance
Olli

**Comment by notenoughtech** [comment]
Awesome. I'll give it a go 😍

**Comment by notenoughtech** [comment]
Hi, 
My apologies for the late reply. Other projects got in the way before I could jump on this with the feedback. 

It's nice to see the events share the details with MQTT, thank you. I have a couple of suggestions:

Spool deselected:
databaseId = null;   - would be cleaner to retain the ID of the active spool otherwise, I have to keep track of the spoolId assigned to the toolId

spool object - any chance to expose all details from spool added event? (brand, cost comments all shebang) 

edits to spools - no event is being fired. That would be ok, if either whole spool object is shared via MQTT on load, or perhaps drop the array of spools with manual refresh in the plugin page?

Thank you for the changes made so far.

**Comment by notenoughtech** [comment]
I came up with a workaround for now (cloning the db file). Not the prettiest way but it works. If you want to see what I made with that - check out this: https://notenoughtech.com/3dprint/smart-filament-storage/
