### ISSUE TITLE
When Printing. The offset value is not applied as per spool manager.

### ISSUE THREAD

**Issue by andycarver101** [OllisGit/OctoPrint-SpoolManager#249]
Windows 10 Pro 21H2
OctoPrint 1.7.3 Python 3.10.1

![image](https://user-images.githubusercontent.com/7031077/156120527-07f0effe-d4f3-471b-bb9f-11595c8ef511.png)
Spool Offset Ignored
I have restarted the Octoprint server and reconnected the Printer. The Job still prints with the values as per the slice profile.

What am I doing wrong?

**Comment by OllisGit** [comment]
Hi @andycarver101, 
new Version 1.7.0 is released and fix the issue. The offset is now applied before printing instead during printing.

Please test and give feedback.

Thx, in advance
Olli
