### ISSUE TITLE
wrong Homepage link

### ISSUE THREAD

**Issue by spanzetta** [OllisGit/OctoPrint-SpoolManager#25]
the Homepage link points to a wrong link
https://github.com/you/OctoPrint-SpoolManager
instead of
https://github.com/OllisGit/OctoPrint-SpoolManager

![image](https://user-images.githubusercontent.com/49818743/89614556-fbccb100-d884-11ea-9956-7d5dac12e89e.jpg)

**Comment by OllisGit** [comment]
Hi @spanzetta ,

thanks a lot, I missed that.

BR
Olli

**Comment by OllisGit** [comment]
Fixe in latest version 1.0.0
