### ISSUE TITLE
Tool not being selected properly for printing

### ISSUE THREAD

**Issue by beardedbrewguy** [OllisGit/OctoPrint-SpoolManager#251]
Hello,

Using a Prusa i3 MK3S+ with MMU2S and the spool manager plugin. When in single nozzle mode, the printer asks which one of the 5 tools i want to use to print with. The plugin is not changing to the tool selected and stays stuck on Tool-0 and as such does not count the filament used for the job. Selecting a filament from within the plugin with the "Select Filament" button does nothing either. Was using Filament Manager previously which functions properly and integrates correctly with the MMU2 Select Filament plugin as well.

**Comment by OllisGit** [comment]
Hi @beardedbrewguy,
I am not sure if I understand you correctly. I understand this:

- You use: https://plugins.octoprint.org/plugins/mmu2filamentselect/ 
- You expect that after select one of the 5 spools the selected spool should also be selected by the SpoolManager

E.g. "PETG Ornage" selecetd for tool0
![image](https://user-images.githubusercontent.com/24205767/159025513-4d0d4201-0982-4e00-8c3d-9946a50527d9.png)

![image](https://user-images.githubusercontent.com/24205767/159026675-5fc5f203-d45a-4da1-a6a4-8d3f01312936.png)

I don't have a Prusa MMU, so I don't know that there is a plugin which interact with FilamentManager/SpoolManager.

Please give my more more details (e.g. with screenshots). Maybe it is related to the MMU-Plugin, did you raise an issue there?
