### ISSUE TITLE
ETA of 1.7.0 ?

### ISSUE THREAD

**Issue by TheStigh** [OllisGit/OctoPrint-SpoolManager#252]
Hi @OllisGit When do you expect the release of 1.7.0? Waiting for the MQTT support :)

**Comment by OllisGit** [comment]
Hi @TheStigh, 
new Version 1.7.0 is released.

Please test and give feedback.

Thx, in advance
Olli

**Comment by sargonas** [comment]
I'm not OP and I can't speak to what needs they wanted served by the MQTT, but having played around with it myself that last few days, it's a thumbs up from me!
