### ISSUE TITLE
Easier way of selecting filament

### ISSUE THREAD

**Issue by benwrth** [OllisGit/OctoPrint-SpoolManager#253]
Hi there,
I am linking using this plugin to manage how much filament each print is using however I have found it to be a bit tedious to select which roll of filament to use.

What if there was a widget in which you could select filaments quickly and easily as so:
![image](https://user-images.githubusercontent.com/66076534/158877519-0a8c4b74-2e5c-4f72-9d59-2292aa538591.png)

Or even just a dropdown would be fine for many.

As far as I'm aware, there is nothing like this, however if I've missed something please do let me know!

Thanks,
Ben.

**Comment by OllisGit** [comment]
Hi @benwrth,

in one of the early versions I had a simple dropdown, but the the "community" wants more filter-options.
Now it looks like this:
![image](https://user-images.githubusercontent.com/24205767/159050786-db80571a-a800-4065-9672-28a3269e8b80.png)
![image](https://user-images.githubusercontent.com/24205767/159051105-a51ea450-c70b-49d3-b42b-bd879c819fd9.png)

Your screenshot looks interesting for single tool-head printer, right? And the printer button is only enabled after a file is selected, right?

...hmmmm...maybe a plugin settings: toggle between show "quick selection" or show "advance filter selection" view.

**Comment by benwrth** [comment]
Hi @OllisGit,
Thanks for your response. I was not even aware of the current widget so that was a surprise!

> Your screenshot looks interesting for single tool-head printer, right?

Yes, thanks. I did forget to consider multiple head setups whle making this as I only really considered my own use case. Whoops!

> the printer button is only enabled after a file is selected, right?

This mockup was based off the File Manager widget so that was the icon that was there previously, maybe something which resembles selecting it would be more appropriate.

I think adding that toggle you mentioned in settings would be a good option as it gives people most choice and flexibility.

Thanks,
Ben.
