### ISSUE TITLE
Needed filament could not be calculated

### ISSUE THREAD

**Issue by maceide** [OllisGit/OctoPrint-SpoolManager#255]
Im having this message pop up all the time when starting prints..

![image](https://user-images.githubusercontent.com/6266042/162052644-b1a0d833-c3b8-4809-938e-8100a08cdaa6.png)

**Comment by GaryStebbins** [comment]
I am having the same issue.

**Comment by rhamkot** [comment]
Having the same issue here

**Comment by Poporacer** [comment]
Same issue here

**Comment by rhinomods** [comment]
I have been having this issue for a long time! starting to get very frustrating. I even reloaded my system that runs octoprint hoping everything being update would fix the issue. 
I have to tell it the same spool about 7-10 times then it finally starts working.

**Comment by Poporacer** [comment]
Still the same issue

**Comment by Poporacer** [comment]
This problem still exists

**Comment by mboehler** [comment]
I have this issue as well.
