### ISSUE TITLE
Does it update the usage after a print?

### ISSUE THREAD

**Issue by spanzetta** [OllisGit/OctoPrint-SpoolManager#26]
I installed it but I found that it doesn't update the used filament for a print
Is it something not implemented yet or do I have some problem?
The quantity of the filament remain always the same even after a print (done with THAT specific spool filament selected before starting the print)
Thanks

**Comment by ScottEgan** [comment]
I am also having this issue. Will try to track down some logs for more info.

**Comment by OllisGit** [comment]
hmm..I could not reproduce the issue, but in the newest version 1.0.0 I added more log-statements.
So, if you test again, please attach the octoprint.log to this issue.

Thx, in advance
Olli

**Comment by ScottEgan** [comment]
I'll install 1.0.0 later today and test it again. Do you think it might have something to do with also having the FilamentManager installed? @spanzetta do you have FilamentManager installed too?

**Comment by OllisGit** [comment]
There should be no conflict between both plugins.

**Comment by ScottEgan** [comment]
Just did some testing. Looks like the usage is correctly updated after the print in the spools tab but not on the state panel (see attached picture). The state panel updates if I refresh the page.
![SpoolManagerUpdate](https://user-images.githubusercontent.com/6709827/90821171-51727600-e2e7-11ea-89e3-ae5a65eedc57.png)

**Comment by OllisGit** [comment]
That shouldn't be the case! I will take al look on this.

**Comment by skimaniac** [comment]
I have the same problem. to test properly I started a new reel and I printed 2 small projects, here is the info gathered by Print Job History

Job 1: 1.81m and 5.44g used
Job 2: 4.26m and 12.82g used
TOTAL: 6,07m and 18,26g used

SpoolsManager recorded -1130mm and -2.9g
FilamentManager recordes 21g used for the 2 job

**Comment by skimaniac** [comment]
I think I found the problem, the octoprint log (octoprint.log) was huge, 350 meg, and I was not able to download it to verify it, finally I deleted it and since that the SpoolManager Plugin works as it should. :)

**Comment by spanzetta** [comment]
> I'll install 1.0.0 later today and test it again. Do you think it might have something to do with also having the FilamentManager installed? @spanzetta do you have FilamentManager installed too?

Sorry for the delay but I am on vacation..
I will check and update when I come back home 
Thanks

**Comment by 5teveO** [comment]
HI Guys as I am not having the filament usage updated also - does this work also for SD card printed jobs (ie started from octoprint) and is it reliant on any other plugins? - I just want to eliminate my newness and any misunderstanding of how this works.

**Comment by OllisGit** [comment]
Hi,

the new version 1.1.0 is out now. This version auto reload the values from the state panel.

Please test and give feedback.

@5teveO I never tested the sd-card approach and at the moment my printer is not working. But maybe someone else could answer the question.

Thx, in advance
Olli

**Comment by 5teveO** [comment]
@OllisGit thanks for the reply - I have updated to latest but no sd card reporting. I have stuttering issues with octoprint so am avoiding printing via the virtual sdcard currently - just starting jobs via octoprint from the printer SD card. No problem just have to remember to add the usage 👍

**Comment by spanzetta** [comment]
now it seems to work fine!
Great job..
Thanks

**Comment by RobeeeJay** [comment]
@5teveO I have been getting stuttering issues too, there is always a huge CPU spike when it happens, I wonder if it's a plugin but I'm not sure what debug/log options to set that might indicate which plugin it is. :(

**Comment by OllisGit** [comment]
Hi @RobeeeJay, @5teveO  ,
if your are using DisplayLayerProgress, then start disabling this plugin. Because a lot of people reported different kind of issues. Maybe that fix your "stuttering".

**Comment by RobeeeJay** [comment]
Unfortunately no, I'm not running DLP :(

The only 3rd party ones are these:

- Access Anywhere - The Spaghetti Detective
- Bed Visualizer
- Cost Estimation
- PrintJobHistory
- PrusaSlicer Thumbnails
- Resource Monitor
- SpoolManager (obviously!)
- Tab Order
- Themeify

Maybe The Spaghetti Detective is a possible cause, but I think SpoolManager is the only other possible cause, but without knowing what to log and what level to log at I can't tell. :(
