### ISSUE TITLE
several issues

### ISSUE THREAD

**Issue by cybernard** [OllisGit/OctoPrint-SpoolManager#267]
The filament amount doesn't work correctly.
I just want to tell it I added a spool with 1kg and that is it.
It won't save it keeps wanting the weight of the empty spool even though I selected "Filament Amount"

I physical can't enter a vendor name, why?  I can enter it, but it won't save it.

**Comment by domRG** [comment]
I found adding spools to be a bit cumbersome too as I was transferring from an excel sheet I was using. I found the csv-import/export functionality to be really helpful in getting this done easily.
I recommend exporting the template as a starting point and then you can set pretty much anything you want - including vendors iirc
