### ISSUE TITLE
Spool Manager no longer calculates remaining weight when printing

### ISSUE THREAD

**Issue by chemixt** [OllisGit/OctoPrint-SpoolManager#272]
Ever since I updated beyond 1.4.3, The spool manager no longer shows any consumption of filament in the data file.  I receive this message every time I print. 

I have installed the latest Spool Manager, (SpoolManager Plugin (1.7.0) and still does not work. 

 I am using a MakerBot replicator 2X.   on Octoprint Version 1.7.3

**" Octopi.local says:
Attention: Needed filament could not calculated (Missing
metadata or spool-fields)
There are no spools selected for the following tools dispite them
being used (maybe) by this print

Tool 0
Tool 1** "

This was originally opened as #218 (ERROR MESSAGE when printing), but was closed without a resolution. 

Update 5-23-2022 - now running Octoprint 1.8, but still same problem

**Comment by timn** [comment]
I'm seeing the same issue, OctoPrint 1.7.3 on OctoPi, plugin version is 1.7.0. Error message is similar, only with Tool 0 to 4 for MMU2S. Spools tab shows all spools as expected. I had one that ran negative that I reset to zero, still no change. Also set all tools to different spools once. The used amount is still deducted from the spools.
