### ISSUE TITLE
QR code page

### ISSUE THREAD

**Issue by 11Daan11** [OllisGit/OctoPrint-SpoolManager#275]
Clicking on the QR code, in the settings page of a spool, gives a new page with a large QR code and the "Database Id" and the "Spoolname" . The spoolname is the same for every spool. Even if Create a new spool. 
Would be handy if the spoolname would be the same as the Displayname in the spool page or if it could be set in the settings page. 

Thanks. 
Daniel

**Comment by nesalkiN** [comment]
Same here.

**Comment by bongo505** [comment]
Same - can confirm the correct QR code is displayed, it is just the title that is incorrect. Use case: I have my filament reels in a home-built dry box. I print the QR codes onto stickers and put in front of the reel so I can easily change in Octoprint when changing filaments.
