### ISSUE TITLE
Spool manger recording exesive amount of filament used.

### ISSUE THREAD

**Issue by navytrav** [OllisGit/OctoPrint-SpoolManager#276]
Recently, Spool manager has been massively over recording usage. For instance, my current spool, which should have about 980G left, shows -101461.1g after about 4 small prints. If I re-weigh it and edit, it will read fine for a print or 2, then mess up. It seems to have started after the OctoPrint 1.8 update or starting to use Octolapse.

**Comment by vaneess** [comment]
I have the same problem, but not so extreme. It is always charged me a little more than was used. Currently shows my spool -6g, which but certainly still has 10-20g left. Is there anywhere to see the individual calculated values? I also use the plugin Print Job History, but according to the description it does not take these values from it yet.
