### ISSUE TITLE
Color change support

### ISSUE THREAD

**Issue by Nohus** [OllisGit/OctoPrint-SpoolManager#278]
When printing with multiple spools (color changes during printing), it is not possible to select correct filament.
When starting a print with color changes, I would expect the plugin to ask for all the spools to be used in sequence.

**Comment by Sembazuru** [comment]
Or, prompt for a new spool at the M600 gcode command.

**Comment by mythmon** [comment]
I don't think this should auto close. This seems like a valuable feature to include.

**Comment by Nohus** [comment]
Activity

**Comment by Nohus** [comment]
Activity

**Comment by Dexter0007** [comment]
When I changed spool in the octoprint while changing filament, the plug-in only subtracted the used amount of filament from the last spool selected.

**Comment by Hottabych-** [comment]
When this can't solved with the MMU2 select Plugin (https://github.com/tkoecker/OctoPrint-Mmu2filamentselect), it would be interesting to support such changes with this plugin . (I haven't tested jet.)

**Comment by TWIISTED-STUDIOS** [comment]
Is no one actively supporting this plugin anymore, this is an issue I have seen raised multiple times and all I see is the bot auto-mark for closure and never actually answers the question of why this doesn't work when its listed as a feature in the features list.

**Comment by Hottabych-** [comment]
It's a pity ...

**Comment by dimo414** [comment]
.

**Comment by Hottabych-** [comment]
reset, bot

**Comment by dimo414** [comment]
.

**Comment by Hottabych-** [comment]
Who has turned the clock?

**Comment by dimo414** [comment]
.

**Comment by dimo414** [comment]
.

**Comment by Hottabych-** [comment]
I fear ... https://github.com/OllisGit/OctoPrint-SpoolManager/issues/333 and hope we get a chance with our wish: https://github.com/OctoPrint/plugins.octoprint.org/issues/1213

**Comment by Hottabych-** [comment]
This is like riding a dead horse ... that's really a pity.

**Comment by dimo414** [comment]
.

**Comment by Hottabych-** [comment]
To be or not to be, that's the question...

**Comment by Hottabych-** [comment]
Good things take time...but not so much.

**Comment by TWIISTED-STUDIOS** [comment]
.

**Comment by Dexter0007** [comment]
.

**Comment by Hottabych-** [comment]
FYI: new maintainer: https://github.com/dojohnso/OctoPrint-SpoolManager/
