### ISSUE TITLE
[Question] How to set the current spool if # is higher than 30?

### ISSUE THREAD

**Issue by 6ffm70** [OllisGit/OctoPrint-SpoolManager#28]
As per title - can't find an option to increase the number of shown spools in the dropdown menu; no button or checkbox in the tab list view, and no option in the detail/edit view.
We have more than 70 spools, the dropdown menu seems to be limited to 30.

**Comment by OllisGit** [comment]
Hi @6ffm70 ,

the limit is removed in the latest version 1.0.0.

**Comment by 6ffm70** [comment]
Full choice of filaments now available in the dropdown menu.
