### ISSUE TITLE
Addd New Spool

### ISSUE THREAD

**Issue by kdennis182** [OllisGit/OctoPrint-SpoolManager#281]
Just installed this add-in and there is no where to add a spool, not on the side bar nor in the add-in settings screen. I can seemingly import a CSV file, but then there is no spools to choose from. I saw this issue in another thread but it did not help. Running the latest version of octoprint on chrome. I have also tried on Microsoft Edge and have the same issue.

**Comment by codefaux** [comment]
I actually just installed the plugin for the first time as well.

Adding a spool is done via the Spools *tab* which is added by the plugin. Ironically, once there, I have added a template but can't seem to add a spool based on the template, so...lol..

**Comment by kdennis182** [comment]
Do no even see a "SPOOLS" tab either on the side bar or under the wrench menu. Figured out how to add via a csv file in the wrench menu then choose a spool and edit the spool thru the side bar but cannot manually add a new spool other than with the IMPORT CSV.

**Comment by kdennis182** [comment]
![image](https://user-images.githubusercontent.com/89350052/178119489-9c3a4574-4b93-42a3-bafa-6effaa64a133.png)

This image does not even exist as far as I can find.

**Comment by codefaux** [comment]
It's not on either side bar. It's not under the Settings (wrench). It's a tab. Temperature, Control, GCode Viewer, Terminal, [...] Spools. It's there with things like the Klipper tab, Cancel Objects, Print Job History plugins. In the image you provided, near the top, you can see the other stock tabs. Its order won't be the same as yours, likely.
If you have a UI customizer installed, make sure it isn't disabling the tab.
There may be a drop-down arrow on the right end of the screen beside the tabs which shows tabs who don't fit.

**Comment by kdennis182** [comment]
Well....There it is! TY codefaux.... Now I love this add--in.....

**Comment by codefaux** [comment]
No worries, it took me a bit to spot it as well. Also @kdennis182 -- be aware of #273 -- Template feature doesn't seem to be working.
