### ISSUE TITLE
Since updating to 1.7.0 Spoolmanager reports spool not selected for printing

### ISSUE THREAD

**Issue by PeterGillham1** [OllisGit/OctoPrint-SpoolManager#286]
After setting up a reel and selecting it for Tool 0, when I click PRINT it says no spools selected OK/Cancel.
![image](https://user-images.githubusercontent.com/93660709/183285767-e85bd046-6000-4882-9ee4-c52f85e6a1fa.png)

Please advise as this was working fine before the updgrade 
![image](https://user-images.githubusercontent.com/93660709/183285855-73c224ad-c131-4998-b836-da9d8be71b81.png)
Please advise

**Comment by melvinmicallef** [comment]
+1

**Comment by EZWoodworker** [comment]
+1
