### ISSUE TITLE
Spool not selecting

### ISSUE THREAD

**Issue by solo2424** [OllisGit/OctoPrint-SpoolManager#290]
When I send a job to OctoPrint from Cura, the spool is not being selected automatically and I am not being prompted to select a spool. In the print details panel, it just says Required Filament unknown.

**Comment by solo2424** [comment]
I since moved to filament manager but would like this issue to be addressed so I can move back to Spool manager. From my understanding, Spool Manager is the replacement to Filament Manager.

**Comment by scurfin** [comment]
Same problem for me, OctoPrint 1.8.6 Python 3.10.6

**Comment by m-klecka** [comment]
Also having this problem, octoprint OctoPrint 1.8.6, Python 3.8.15, Spool manager 1.7.0

**Comment by TheFlamingShark** [comment]
Another one for the pile, same issue, OctoPrint 1.8.6, Python 3.8.15, Spool manager 1.7.0. 
also w/ UI customizer the pop-up saying that a spool isnt selected doesnt appear.
