### ISSUE TITLE
Bed temperature? 

### ISSUE THREAD

**Issue by masterdot** [OllisGit/OctoPrint-SpoolManager#30]
Hey there, just saw you are working on a own spool manager.

I did open a request for filament manager, so I do here also :)

I think of starting working with offsets for temp, so I don't need to  chance the temp in the slicer and maybe reprint with a wrong temp. 

So it would be nice to implement temp offsets for hotend(s) and bed.
Thanks in advance and it looks interesting :) do you plan to migrate the collection from filament manager?

**Comment by OllisGit** [comment]
Added in latest version 1.2.0

Please test and give feedback

Thx, in advance
Olli

**Comment by masterdot** [comment]
It's there and working.
But I had in mind to store the values for the hotend and bed with the spool, so it will be used for printing... My intention was to have a better reuse for sliced prints with different materials without having them to be resliced.

**Comment by WyattNielsen** [comment]
@masterdot storing the temperature as an offset is a feature request see issue #59 I implemented that in a PR that is pending discussion from @OllisGit
