### ISSUE TITLE
When first loading the Spools tab, spools are not visible until performing an action

### ISSUE THREAD

**Issue by tmcgee123** [OllisGit/OctoPrint-SpoolManager#300]
If I don't use a form button when I load the spools page, it does not show spools. There's excessive calls being made to get the list of spools for each part of the query. You can see there are supposed to be spools by the row count in the top of the page.

Once I do something like use the per Page dropdown, it will show the rest of the spools
![onloadSpoolNotShowing](https://user-images.githubusercontent.com/6415216/202826847-2cdfc849-06da-440f-8c0f-270782578d8a.png)

**Comment by Electric3el** [comment]
Same problem here, always need to use the "reload", sort or filter feature to get the list.

**Comment by kaoszwerg** [comment]
same here

**Comment by anthonyptetlow** [comment]
I also have this issue
