### ISSUE TITLE
 Temperature Offset not working

### ISSUE THREAD

**Issue by MarshMalloW0007** [OllisGit/OctoPrint-SpoolManager#305]
Hello Ollis,

I have tested the temperature offset but it does not work.

I have activated the options in the configuration of the plug-in.
![Capture d’écran 2022-12-14 181413](https://user-images.githubusercontent.com/45604136/207680083-1424700a-d8a6-426b-b328-c3b3b050b801.jpg)

I have indicated the offset in the spool configuration.
![Capture d’écran 2022-12-14 181503](https://user-images.githubusercontent.com/45604136/207680308-b736a65b-ca36-4b98-9a20-e140312a55dc.jpg)

The gcode file has a nozzle temperature of 100° and a bed temperature of 10°.
I indicate the offsets 110° and 40° to obtain a final temperature of 210° and 50°.

During the preheating, the temperatures are well reached.
![Capture d’écran 2022-12-14 181241](https://user-images.githubusercontent.com/45604136/207680582-afccc4f1-7415-4468-9011-510179416878.jpg)

But when the printing starts, 
![Capture d’écran 2022-12-14 181308](https://user-images.githubusercontent.com/45604136/207680807-bafc1a43-c38c-43aa-91b9-b79fba15a9be.jpg)
![Capture d’écran 2022-12-14 181342](https://user-images.githubusercontent.com/45604136/207680901-b78d789f-ba2b-4ad2-8b69-bee936f83258.jpg)
the temperature of the nozzle goes down to that of the gcode: 100°. Not that of the bed.

The printing is thus impossible.

**Comment by MarshMalloW0007** [comment]
I did several tests and here is what I found out:
- OctoPrint does not support manual offers greater than 50.
- The bug that I found does not concern this plug-in but directly OctoPrint.

Sorry for the inconvenience.

**Comment by cinghialino** [comment]
@MarshMalloW0007 is there a way to update the code file temperatures with the ones set for the filament spool upon selection?
