### ISSUE TITLE
Cannot install on OctoPrint 1.8.6 and Python 3.9.16

### ISSUE THREAD

**Issue by nodu** [OllisGit/OctoPrint-SpoolManager#311]
OctoPrint 1.8.6
Python 3.9.16

```
2023-02-14 04:32:24,253 ! error in OctoPrint-SpoolManager setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
2023-02-14 04:32:24,258 ! pillow >=6.2.0<7.0.0
2023-02-14 04:32:24,261 ! ~~~~~~~^
```

Editing setup.py and removing the version band for pillow seemingly fixes the install.
```
plugin_requires = [
	"pillow >=6.2.0<7.0.0", # since 7.0.0 no Python 2.7 Support, see https://github.com/python-pillow/Pillow/blob/master/CHANGES.rst
```

to

```
plugin_requires = [
        "pillow", # since 7.0.0 no Python 2.7 Support, see https://github.com/python-pillow/Pillow/blob/master/CHANGES.rst

```

**Comment by dkaser** [comment]
What version of pip do you have installed? I can install just fine without any changes using:

Python 3.10.6
Pip 22.3.1
OctoPrint 1.8.6

**Comment by ronzelver** [comment]
Same here, I cannot install Spool Manager. I have the following versions:

Python 3.9.16
Pip 22.3.1
Octoprint 1.8.6

This is what the octoprint.log shows:
`2023-03-01 21:07:43,359 - octoprint.plugins.pluginmanager - INFO - Installing plugin from https://github.com/OllisGit/OctoPrint-SpoolManager/releases/latest/download/master.zip
2023-03-01 21:07:44,484 - octoprint.plugin.core - ERROR - Error loading plugin SpoolManager
  File "/root/Octoprint/lib/python3.9/site-packages/octoprint_SpoolManager/__init__.py", line 12, in <module>
    from octoprint_SpoolManager.DatabaseManager import DatabaseManager
  File "/root/Octoprint/lib/python3.9/site-packages/octoprint_SpoolManager/DatabaseManager.py", line 9, in <module>
`

**Comment by sammcj** [comment]
Confirming it's a problem for me as well - it seems it doesn't work with the latest OctoPrint (1.8.6) and Python 3.11.2.

After successfully(!?) installing it doesn't show up as installed.

**Comment by ronzelver** [comment]
Why isn't there any response?

**Comment by IchSchreiGleich** [comment]
Same here. Installed setuptools 65.7.0 (any <66+ should work) and the plugin installs.

```
python -m pip install pip==22.3.1
python -m pip install setuptools==65.7.0
python -m pip install wheel==0.38.4
```

**Comment by ronzelver** [comment]
> Same here. Installed setuptools 65.7.0 (any <66+ should work) and the plugin installs.
> 
> ```
> python -m pip install pip==22.3.1
> python -m pip install setuptools==65.7.0
> python -m pip install wheel==0.38.4
> ```

You mean that the plugin is visible and functional? I've installed the same version you mentioned, but I still have the same result i.e. install completes but the plugin is not there after restarting Octoprint.

**Comment by IchSchreiGleich** [comment]
> You mean that the plugin is visible and functional? I've installed the same version you mentioned, but I still have the same result i.e. install completes but the plugin is not there after restarting Octoprint.

Yes, it is fully functional. My mistake was that I was looking in the wrong place, it is configurable in OctoPrint Settings > Plugin > Spool Manager. But I was wondering how to add a spool. It's not very intuitive as the menu item is overhanging in my installation (too many plugins maybe) and is next to the virualization of temperatures, terminal commands, etc.
