### ISSUE TITLE
Feature request: Enter new spools by length

### ISSUE THREAD

**Issue by Spacemarine2018** [OllisGit/OctoPrint-SpoolManager#32]
When editing a spool, I can adjust the field "used length", but there are no fields like "total length" and "remaining length". However, it would be useful to have these fields also available for cases where I only have a certain length available (small sample spools, etc.) Since I do all calculations in directly in the unit length, it would be an unceccessary step to convert to weight just to be able to use the plugin.

**Comment by OllisGit** [comment]
Added in latest version 1.2.0

Please test and give feedback

Thx, in advance
Olli

**Comment by 5teveO** [comment]
Can I ask if the plugin is meant to calculate spool length by weight? ie put in eg 1250g total - 250g spool - add density and dia/ tolerance - the total length is then calculated?

**Comment by Spacemarine2018** [comment]
@OllisGit Thanks for implementing this fuction! I'm happy to see this plugin grow so fast!

Now I can enter the fresh length and the remaining length. However, it seems that for most displays the weight is still required. 

For example: The plugin box on the lower left side will not show any information if I only enter the length of the filament. And also the overview in the main tab doesn't show the remaining length, only the used length.
