### ISSUE TITLE
BUG: When Scanning QR Code of different spools, only spool 1 is selected for printing

### ISSUE THREAD

**Issue by ScottGibb** [OllisGit/OctoPrint-SpoolManager#329]
# Issue

When using the plugin, I found that no matter which spool QR Code I scanned, the plugin would always select spool 1 in the database for printing. I'm running an iPhone 13 with the built-in QR Code Scanner, opening the webpage in Safari. When I scanned spool 2 in the database through the UI, the following link was created:

_http://wanhaoprint.local/login/?redirect=%2F%3F&permissions=STATUS%2CSETTINGS_READ#tab_plugin_SpoolManager-spoolId2_

It would seem that the URL is being created correctly, however possibly not being handled on the other side correctly.

A part of this, awesome plugin!!! Really enjoy using it, and looking forward to getting it integrated with my Label Maker!! (#325) 

# Steps to Repeat

- Use an iPhone 13 QR Code Scanner
- Scan the QR Code on a spool that isn't the first in the database.
- Plugin selects spool 1 for printing

Ticket #185 says this was fixed in V1.5, in my system i'm running V1.7.

# Hardware/Software Setup

- OctoPrint-SpoolManager v1.7
- Octoprint Version 1.8.7
- Raspberry Pi 3

**Comment by normen** [comment]
Same here when using the direct link like `http://octopi/plugin/SpoolManager/selectSpoolByQRCode/6`

Edit: Add to that when displaying the QR code it always shows the name of the first spool as well, even though it shows different ID's

**Comment by normen** [comment]
bump

**Comment by normen** [comment]
Meep

**Comment by ScottGibb** [comment]
moop

**Comment by mdziekon** [comment]
This issue most likely has been already fixed in my fork of the plugin, see:
https://github.com/mdziekon/OctoPrint-SpoolManager/issues/37

**Comment by ScottGibb** [comment]
@mdziekon Awesome, il give it a shot this weekend hopefully. Is there anyway to keep my database for spools intact when uninstalling this plugin and then installing yours?

**Comment by mdziekon** [comment]
@ScottGibb when using either URL or ZIP install, my fork should simply replace your installed original plugin, without affecting the DB. To be safe, make sure to perform a DB backup though.

**Comment by ScottGibb** [comment]
@mdziekon Sorry for taking so long to test it, but I've now installed your plugin, and tried both 1.8 and 2.0 and both do not work, The same issue as before keeps happening. When you scan the QR code it creates the correct URL as before, however, it continues to select the first spool in the database.

**Comment by normen** [comment]
huargh

**Comment by ScottGibb** [comment]
beep

**Comment by ScottGibb** [comment]
bump

**Comment by normen** [comment]
I switched to this branch, seems to have all the fixes we need: https://github.com/jkotowicz1/OctoPrint-SpoolManager

Its settings are compatible, you just need to uninstall this version and install that version above using the .tar.gz file

Edit: Fixed link

**Comment by ScottGibb** [comment]
@normen Cheers for the link, sadly that repo also has the same issue as this. I'm gonna copy and paste the issue into that repo and see what happens

**Comment by normen** [comment]
> @normen Cheers for the link, sadly that repo also has the same issue as this. I'm gonna copy and paste the issue into that repo and see what happens

Sorry, I gave the wrong link, this is the version I have installed (so many forks!)
https://github.com/mdziekon/OctoPrint-SpoolManager

**Comment by ScottGibb** [comment]
@normen Just installed the Spool Manager from mdziekon. Still seem to be getting the same issue. I installed it using the zip location link 
https://github.com/mdziekon/OctoPrint-SpoolManager/releases/latest/download/master.zip
Which then looks like this:
![image](https://github.com/OllisGit/OctoPrint-SpoolManager/assets/44235263/201786b1-fd1f-4035-b5cd-179a859fe2f5)

But still seem to be getting the same functionality. Any ideas? You mentioned using the tar.gz, how did you go about installing it through that?

**Comment by ScottGibb** [comment]
@normen Ive created a new issue on the forked repository you added https://github.com/mdziekon/OctoPrint-SpoolManager/issues/52

**Comment by normen** [comment]
Omg, could it be this one? It has the links to the mdziedkon one so it looks like that in the settings for me too.. 😕

https://github.com/jkotowicz1/OctoPrint-SpoolManager

**Comment by ScottGibb** [comment]
@normen YESSSS!!!! That is the one that works, so so many forks hahah. For anyone that comes across this issue: This is the fork you want to use:
https://github.com/jkotowicz1/OctoPrint-SpoolManager

Also special thanks to @normen for finding a fork in which the QR code scanning works!!

IMPORTANT:
The repo linked above uses an old install link in the readme. Instead, go directly to releases and download the release manually. Then install this zip by uploading to octoprint over the LAN

**Comment by ScottGibb** [comment]
@normen, the other repository that @mdziekon made also has the bug fix with more features. If your interested, here is the issue discussion, where mdizekon helps me fix the qr bug, needed to checkout the prerelease code.
https://github.com/mdziekon/OctoPrint-SpoolManager/issues/52
