### ISSUE TITLE
Confirmation dialog doesn't appear always

### ISSUE THREAD

**Issue by Spacemarine2018** [OllisGit/OctoPrint-SpoolManager#33]
I have actived the following option: "Reminder for verifying the selected spool."

When I click on the big print button in the status field, I get asked for confirmation.
But when I click the small print button in the files field, the print starts without the confirmation.

**Comment by OllisGit** [comment]
Hi @Spacemarine2018 
fyi: I looked into the OctoPrint-Sourcecode and it behaves differently (printbutton vs. file-print). IMHO this is a bug, so I will raise a ticket.

**Comment by antoniobeta** [comment]
Hi @OllisGit 
I also want you to know that the dialog doesn´t appear when you start the print with a program that uses the Octoprint API. 

In my case I start the prints directly with Prusaslicer (they start automaticaly when it sends the GCODE to Octoprint) and I never get the pop up.

**Comment by OllisGit** [comment]
Hi @antoniobeta ,
a the moment I hijack the button clicks to prevent starting the print.

If the print is started via API, it is not so easy to interrupt the print.
- Maybe the UI is not open, what should the plugin do? 
  Abort the print or pause the print till the User open the UI and confirm the dialog

**Comment by OllisGit** [comment]
Hi @Spacemarine2018,
in the latest version 1.1.0 the small print button now also activate the PopUp.

Please test and give feedback.

Thx in advance,
Olli

**Comment by Spacemarine2018** [comment]
Hi @OllisGit 

I tested it and it works perfectly. Thanks a lot, that will improve my workflow!
