### ISSUE TITLE
M600 support

### ISSUE THREAD

**Issue by blackboxgeeks** [OllisGit/OctoPrint-SpoolManager#34]
Will you be adding in support for M600 gcode commands?

**Comment by OllisGit** [comment]
Hi @blackboxgeeks ,

I added your feature request to the long term column: https://github.com/OllisGit/OctoPrint-SpoolManager/projects/1

**Comment by NLH-Software** [comment]
Isn't this something like #18 
But would like to see this implemented, too.
Had a print two days ago, which used a filament change. Afterwards I had to edit the spools to correct the used lengths and weights manually.

**Comment by codingcatgirl** [comment]
Hm. this shouldn't be closed. i'd really likeif i had *any* way to change the spool mid-print, doesn't even matter how complicated it is. With Filament-manager you can pause the print and change the filament selection. With SpoolManager, not even that is possible. This makes it impossible to come up with any workarounds for multi-filament prints until that feature is implemented. 

I feel like a lot of people (including me) are in dire need for (at least) a workaround of this issue,

**Comment by OllisGit** [comment]
Hi,

I retested the behaviour with the latest release (V1.6.0) with this test-script in my virtual printer.
I changed the spool during the pause and at the end of the print both spools were updated correctly. 
```
G28
M83; relative extruder
G1 F1000
G0 E1000
M600
G0 E500
```

Please do me a favour and test this in your environment.

Thx, in advance
Olli
