### ISSUE TITLE
Question How do I adjust to improve accuracy

### ISSUE THREAD

**Issue by lathemaster** [OllisGit/OctoPrint-SpoolManager#342]
Love the plugin. Used it through 3 spools. seems to be overestimating filament usage by about 15-20%
Is this corrected by Flow Rate Compensation if so how
Thanks in advance
Mike

**Comment by vaneess** [comment]
same here! i've calibrated my extruder and setup the correct data of the spool, but my spools are shown as empty when i still have about 100g or more on a 1000g original spool
