### ISSUE TITLE
When uploading new print the warning about unselected spools occurs

### ISSUE THREAD

**Issue by Letme** [OllisGit/OctoPrint-SpoolManager#345]
You do print 1, select spools and start the print. Once print completes (failure or not), you select print 2, spools below in UI remain the same, but when you click Print, it tells you Tool 0 and Tool 1 are not selected. Sometimes you delete selection of 1 spool and reselect the same spool from lets say Tool 0 and you can print (both Tools then have spools - no warning), but other times I need to delete both spools and reselect them.

**Comment by wizardkitty** [comment]
This plugin saddly is abandoned.

**Comment by Letme** [comment]
Activity.
