### ISSUE TITLE
Fails build through plugin manager or URL

### ISSUE THREAD

**Issue by alien8r** [OllisGit/OctoPrint-SpoolManager#346]
Building wheel for OctoPrint-SpoolManager (setup.py): finished with status 'error'
Running setup.py clean for OctoPrint-SpoolManager
error: subprocess-exited-with-error

× python setup.py bdist_wheel did not run successfully.
│ exit code: 1
╰─> [215 lines of output]
Found packages: {'octoprint_SpoolManager.common', 'octoprint_SpoolManager', 'octoprint_SpoolManager.api', 'octoprint_SpoolManager.models'}
running bdist_wheel
running build
.....
File "/home/pi/OctoPrint/venv/lib/python3.9/site-packages/wheel/vendored/packaging/_tokenizer.py", line 163, in raise_syntax_error
raise ParserSyntaxError(
wheel.vendored.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after version specifier)
pillow>=6.2.0<7.0.0
~~~~~~~^

**Comment by alien8r** [comment]
Tried various fixes, all useless.
No input at all from maintainer.

**Comment by drohhyn** [comment]
There is a fork which is already in the plugin repo: https://github.com/dojohnso/OctoPrint-SpoolManager
