### ISSUE TITLE
Cannot import from .csv

### ISSUE THREAD

**Issue by molodeztom** [OllisGit/OctoPrint-SpoolManager#36]
I export existing database to .csv. Without editing I import the same .csv. I got an error:
Mandatory column is missing 'Spool Name'. 
The first column has headline Spool Name. 
![image](https://user-images.githubusercontent.com/13887230/91057274-48571100-e627-11ea-8e8e-33c61fc03b92.png)
I do not get it. As a minimum I could create a .csv (in Excel) with only one column Header Spool Name and Rows with different names. When I try to import it takes for ever Status: running Importing line: 2. 
What do I make wrong?

**Comment by OllisGit** [comment]
Hi @molodeztom!

Please attach your CSV-File to this issue so that I can take a closer look. 

What System to you use: Linux, Win, Mac, Browser, OP-Version, Python?

**Comment by molodeztom** [comment]
Hi ,
it works now. SpoolManager1.csv works ..2.csv not. You may have a look but for me it is ok now. 
[Documents.zip](https://github.com/OllisGit/OctoPrint-SpoolManager/files/5122849/Documents.zip)
I have entered serveral spools with the UI and it works fine.
I use Windows10 Excel to edit the file and Raspbi 3B+ with octopi Image.
Thank You is a really helpful plugin.
Thomas
