### ISSUE TITLE
[Enhancement] prefill filament diameter value for new spools

### ISSUE THREAD

**Issue by hamster65** [OllisGit/OctoPrint-SpoolManager#37]
I think most printers only use one diameter (which could be pre-set in the options), so it would make sense to pre-fill that value for new spools.

**Comment by OllisGit** [comment]
Hi @hamster65 ,

you can define a "Template-Spool". Each time you create a new spool, values from the template spool are predefined in the new spool.
Please try!

**Comment by hamster65** [comment]
Great, thanks!
