### ISSUE TITLE
Euros to USD?

### ISSUE THREAD

**Issue by spinracing** [OllisGit/OctoPrint-SpoolManager#43]
Is there a method to change the Euro designation for cost to USD?

**Comment by skimaniac** [comment]
> Is there a method to change the Euro designation for cost to USD?

SpoolManager setting -> General TAB -- Currency symbol 
<img width="936" alt="Capture d’écran, le 2020-08-26 à 21 01 17" src="https://user-images.githubusercontent.com/44727542/91371727-c9590880-e7df-11ea-940d-3d235d8517d1.png">
