### ISSUE TITLE
In the files list show filament usage in grams instead of volume

### ISSUE THREAD

**Issue by eraxar** [OllisGit/OctoPrint-SpoolManager#44]
Hi there, in the old Filament Manager it shows the filament usage in the files list in grams instead of volume (see screenshot) may you can add this to the spools manager?
![octorpint_files_list](https://user-images.githubusercontent.com/29177516/91442786-a9bef000-e872-11ea-98b1-537f59e6bcf7.png)

**Comment by OllisGit** [comment]
fyi: will be added during implementation of "multi-tool support"

**Comment by TheHolyRoger** [comment]
Hey @OllisGit was this removed? I don't see the estimated grams in the files list, only in the "loaded" file. The old filament manager plugin used to show the grams for every file (when you click the arrow to expand)

**Comment by B1ackCr0** [comment]
Just came here looking for the same thing.  I don't see it working on v1.7
