### ISSUE TITLE
Feature Request: sort by type of material

### ISSUE THREAD

**Issue by skimaniac** [OllisGit/OctoPrint-SpoolManager#45]
I would like to be able to sort by type of material please.
Thank you

**Comment by OllisGit** [comment]
Hi @skimaniac,

this feature is now implemented in version 1.1.0.

Please test and give feedback.

Thx, in advance
Olli

**Comment by skimaniac** [comment]
as soon as i can update i check that. Thank you!

**Comment by skimaniac** [comment]
It works perfectly, thank you again!

The only small problem is that octoprint did not offer me the update, I had to go to Install new plugin and click on reinstall. It may be that the first installation I did was with the url.
