### ISSUE TITLE
Feature Request MMU2 aka MultiTool Support

### ISSUE THREAD

**Issue by kalleknall** [OllisGit/OctoPrint-SpoolManager#46]
Multitool Support is needed to replace the old Plugin. It is so great to have 5 Filaments loaded for single Material prints.

Please plan it for short term devlopment. I think the most MMU Users needs this Feature.

Great Work so far !!!

**Comment by codingcatgirl** [comment]
Yes! Please add this!

This plugin is awesome and i've been waiting something to finally replace the filament manager. However, i'll start using an MMU in a few days, so there is no use in migrating to this plugin for me yet if it won't support multi-material prints.

Looking forward to this :)

**Comment by Zinip** [comment]
As soon as this gets this multi-tool/MMU2 suuport I'm going to be all over over, I can't wait! 

> Multitool Support is needed to replace the old Plugin. It is so great to have 5 Filaments loaded for single Material prints.
> 
> Please plan it for short term devlopment. I think the most MMU Users needs this Feature.
> 
> Great Work so far !!!

I can't agree with this any more... I'll be keeping on eye out for this feature to get put in, because once it does I'm going to be all over this. I haven't been this excited for a Plug-in since finding Filament Manger like well over a year ago!

**Comment by comm** [comment]
Definitely support this request - I was enjoying using this plugin before I got my MMU unit but have had to stop. Happy to support - fundamentally its linking the "Extruders" defined in Octoprint to a spool.

Really look forward to this being implemented ASAP.

**Comment by rickyh777** [comment]
I too would love to see this! For now I manually select when I have it in single spool mode but disable when doing multi prints. Otherwise great plugin!

**Comment by codingcatgirl** [comment]
Stalebot being unproductive and problematic as usual. Do i have to set a reminder to post in this issue ever 29 days or can you please disable it?

**Comment by codingcatgirl** [comment]
Good morning, before stalebot markes this issue for auto close again, i'd like to say that i'm still very much hoping that this will be implemented eventually. :)

**Comment by Zinip** [comment]
I'll tackle this bi-weekly bump, as I also have continued hope for this! ...One might even be able coerce some begging out of me, if absolutely necessary. 😅

**Comment by OllisGit** [comment]
fyi: this is the next big thing (in front of "external database"")

**Comment by codingcatgirl** [comment]
Since i really needed this feature right now, i decided to just implement it myself :) I have most parts already done and only need to adjust a few things before i can submit a pull request – should be done by tomorrow or at least this weekend!

**Comment by codingcatgirl** [comment]
Here we go: Please test :) #161
