### ISSUE TITLE
Change Name in Settings from "SpoolManager Plugin" to "Spool Manager"

### ISSUE THREAD

**Issue by codingcatgirl** [OllisGit/OctoPrint-SpoolManager#47]
For some reason, in the Octoprint settings, the word "Plugin" is prepended is to the name of the Settings section associated with it.

That seems a bit pointless and redundant to me and i assume it's a mistake :D Please change it.

**Comment by OllisGit** [comment]
Hi @codingcatgirl ,

did you test your PR? Your change has no effect to the settings menu.

I looked a little bit deeper  into the OP-Code and found the issue. The menu use the plugin_name variable.... that was the reason why I didn't change it in the past for my other plugins.

BUT, I raised a PR for OctoPrint to provide customisation of the Linkname: 
https://github.com/OctoPrint/OctoPrint/pull/3710

Maybe we have success and the PR is excepted....will see!

**Comment by codingcatgirl** [comment]
Oh wow, no i have to admit i didn't test it because it really didn't expect there to be any other possible cause. Thanks for taking care of it though :)

**Comment by OllisGit** [comment]
Hi @codingcatgirl,

the name is now adjusted in version 1.1.0..

BR
Olli

**Comment by codingcatgirl** [comment]
I saw, awesome!
