### ISSUE TITLE
Currency symbol does not change

### ISSUE THREAD

**Issue by Lumute** [OllisGit/OctoPrint-SpoolManager#48]
Hi, 

Thanks for the great plugin!

I changed the currency symbol to $ but when I edit an spool I still see € nest to the Cost field.

**Comment by OllisGit** [comment]
Hi @Lumute,
in the latest version 1.1.0 the Settings-Value is now reflected to the edit-dialog.

Please test and give feedback.

Thx, in advance
Olli

**Comment by Lumute** [comment]
Looking good, Thanks so much!
