### ISSUE TITLE
Feature Request: Select columns to be shown in overview

### ISSUE THREAD

**Issue by NLH-Software** [OllisGit/OctoPrint-SpoolManager#51]
Requesting a settings feature, to select the columns which should be shown in the overview.
In my case I would like to hide the Note column and instead want to show the temperature column, because this value would be much more interesting for me.

**Comment by OllisGit** [comment]
Hi @NLH-Software,
this feature is now implemented in version 1.1.0.

Please test and give feedback.

Thx, in advance
Olli
