### ISSUE TITLE
No 1.1.0 in Software update

### ISSUE THREAD

**Issue by jmarc67** [OllisGit/OctoPrint-SpoolManager#54]
Hello,

I cannot see 1.1.0 SpoolManager plugin in Software update.
No update even with "Force check for update" option

![image](https://user-images.githubusercontent.com/58570258/91940044-23cdf980-ecf7-11ea-8efd-98e72dceeb71.png)

Here is what i have above.
(Release note is empty)

**Comment by OllisGit** [comment]
I takes some time. Please do the following:

- Filter: Spool
- You will see version 1.0.0
- Open menu and click on "refresh"
- Now you can (should)see version 1.1.0 
![image](https://user-images.githubusercontent.com/24205767/91943722-52e76980-ecfd-11ea-96f6-318f05eaacaf.png)

**Comment by jmarc67** [comment]
I've done that and:

![image](https://user-images.githubusercontent.com/58570258/91950527-b1faad80-ed00-11ea-92eb-77b8a896df9b.png)

Something strange because i had "Reinstall" and not "install"
