### ISSUE TITLE
Feature Request: Add selected job weight

### ISSUE THREAD

**Issue by abrenoch** [OllisGit/OctoPrint-SpoolManager#57]
I think the one feature I am missing from the old [Filament Manager Plugin](https://plugins.octoprint.org/plugins/filamentmanager/) is the ability to replace the selected job volume with weight instead (in the sidebar when the job is selected). I personally just find that information more applicable... Would be nice to see it implemented thru this plugin as well!

Thanks for the **great** work on this!

**Comment by OllisGit** [comment]
Hi @abrenoch ,

sound like this ticket #44. If so, please close your ticket and track the progress there.

Thx,
Olli

**Comment by abrenoch** [comment]
Sure does, must have missed that!
