### ISSUE TITLE
Database File Location fixed 

### ISSUE THREAD

**Issue by david-hinchliffe** [OllisGit/OctoPrint-SpoolManager#60]
It would be good to be able to select a different location for the database file. I would like to move it to a mapped drive to lessen the read/writes on the sd card (Raspberry pi)
![Annotation 2020-09-08 135011](https://user-images.githubusercontent.com/11887459/92478715-78cbad00-f1da-11ea-8f2f-57b620d93152.png)

**Comment by Quintin9801** [comment]
@david-hinchliffe @OllisGit 
I agree that being able to change the file location of the database would be helpful. I work on many different octoprint instances and it would be nice for them all to use the same database file so they are "in sync" with one another. I have approx. 68 spools in my inventory and tracking them across instances would save a lot of time! cannot wait for the eventual barcode/QR feature to make this process even more smooth.
