### ISSUE TITLE
Feature Request: start after x seconds

### ISSUE THREAD

**Issue by AJErazzor** [OllisGit/OctoPrint-SpoolManager#62]
Would it be possible to throw up the warning about the filament color check for x seconds and if not changed then start the print?  I like having the check there - but often I am doing multiple prints on the same spool and keep forgetting to confirm only to come back and the print not started.

**Comment by OllisGit** [comment]
You mean something like in my "Autostart-Plugin"
https://github.com/OllisGit/Octoprint-AutostartPrint
![image](https://user-images.githubusercontent.com/24205767/93929136-b15fa080-fd1b-11ea-835b-05f5ac15fcb1.png)

**Comment by AJErazzor** [comment]
Yes exactly like that but driven from when I click print button - shows the message about the spool selected and then starts the countdown
