### ISSUE TITLE
Where do I select a Spool for printing

### ISSUE THREAD

**Issue by war1000** [OllisGit/OctoPrint-SpoolManager#65]
Hi, this is a bit of headscratcher for me. I put in the spool info to the best of my knowledge but where do I select the spool? When I try to print, it does give me the warning that a spool has not been selected and if I should proceed without one. But I can't find the option to select the spool. Can you please point it out to me? Thanks!

![image](https://user-images.githubusercontent.com/57807544/93894450-bd684580-fcbc-11ea-8836-9bd7dcd7dec0.png)

**Comment by 5teveO** [comment]
Bottom Left hand corner of the Octoprint Main page..  under spool manager plugin, under printer notifications!

**Comment by ThomDietrich** [comment]
Recommend to install https://plugins.octoprint.org/plugins/dragon_order then Drag&Drop the Dialog further up
