### ISSUE TITLE
"Load and print" may bypass spool manager

### ISSUE THREAD

**Issue by AJErazzor** [OllisGit/OctoPrint-SpoolManager#66]
If I choose an already uploaded model I have printed before and choose load and print the job starts straight away and I’m not asked to confirm spool - I don’t know if the job is then monitored for filament use or it’s being bypassed

**Comment by OllisGit** [comment]
Hi @AJErazzor,

reprinting the same model should also show a "confirm-dialog". Sounds like a bug.

PS. Sorry, for being late to the party, but I made a "Octoprint sabatical" (no coding, no printing) the last months.

**Comment by OllisGit** [comment]
Hi @AJErazzor,
fyi: I could reproduce the error and it will be fixed in the next release.

**Comment by OllisGit** [comment]
Hi @AJErazzor,
fixed is in latest release v1.3.0

BR
Olli
