### ISSUE TITLE
verify selected spool 

### ISSUE THREAD

**Issue by slippy115** [OllisGit/OctoPrint-SpoolManager#67]
keeps telling me to verify selected spool  how do i do that

**Comment by Yang-Richard** [comment]
I'm also curious how to do this. I can't find a settings page or area to verify the selected spool, even though I have a spool selected and it automatically decreases the remaining spool percentage after prints.

**Comment by ThomDietrich** [comment]
This is just an unfortunately phrased request to confirm your selection. See #74

**Comment by ThomDietrich** [comment]
@OllisGit is stalebot closing tickets in your absence really intended? The bot became quite popular over the years but I am convinced that in small less active repositories it does more harm than good.

**Comment by OllisGit** [comment]
Hi @slippy115, @Yang-Richard,

the PR from @ThomDietrich will be in the next release.
  
PS. Sorry, for being late to the party, but I made a "Octoprint sabatical" (no coding, no printing) the last months.

**Comment by OllisGit** [comment]
Hi,

PR is implemented in latest release 1.3.0.

Please test and give feedback.

Thx, in advance
Olli
