### ISSUE TITLE
Enclosure misspelled as Encloser

### ISSUE THREAD

**Issue by ericsnis** [OllisGit/OctoPrint-SpoolManager#68]
It doesn't effect the functionality, so this is pretty minor.

Enclosure is misspelled "Encloser" at the bottom of the spool details dialog.

![image](https://user-images.githubusercontent.com/34842376/94581047-3aa53480-0240-11eb-8547-07df4356f97b.png)

**Comment by OllisGit** [comment]
Hi @ericsnis ,

thx for reporting, will be fixed in next release.

PS. Sorry, for being late to the party, but I made a "Octoprint sabatical" (no coding, no printing) the last months.

**Comment by OllisGit** [comment]
Hi @ericsnis,
fixed in latest release v1.3.0.

BR
Olli
