### ISSUE TITLE
Some spool colors do not showup in spool list

### ISSUE THREAD

**Issue by theone11** [OllisGit/OctoPrint-SpoolManager#70]
When choosing custom color #xxxxxx in spool information page **most of the times** the color doesn't show up i the spool list.
It **always** shows up in the spool inforamtion page

For example when chossing color LightSkyBlue #87CEFA it does show up in spool information:
![image](https://user-images.githubusercontent.com/3348953/95023429-abf04780-0685-11eb-93fe-f7f194d83fb4.png)
but not in spool list:
![image](https://user-images.githubusercontent.com/3348953/95023419-a2ff7600-0685-11eb-8cab-d75a609d466a.png)

and for another custom color DarkVoilet $9400D3:
![image](https://user-images.githubusercontent.com/3348953/95023463-cfb38d80-0685-11eb-8c24-4965ccbc85f2.png)
It does show up:
![image](https://user-images.githubusercontent.com/3348953/95023479-ebb72f00-0685-11eb-9460-7fbb28683978.png)

All my color definitions where taken from
https://www.w3schools.com/colors/colors_groups.asp

**Comment by OllisGit** [comment]
Hi @theone11 ,
you copy and pasted the color-value plus the starting # in the first picture. So, in the database we have two hash-signs:

![image](https://user-images.githubusercontent.com/24205767/95556853-42b95d00-0a14-11eb-8314-faa34e469c23.png)

I need to fix this behaviour.

**Comment by OllisGit** [comment]
Hi @theone11,
fix is in lates release v1.3.0

BR
Olli
