### ISSUE TITLE
"save" button is not accessible

### ISSUE THREAD

**Issue by skimaniac** [OllisGit/OctoPrint-SpoolManager#71]
The "save" button is not accessible in normal screen mode on a macbook pro 13 ". The box to add comments is displayed over the button and prevents pressing" save "we must absolutely switch to full screen mode .

Normal screen
<img width="559" alt="Affichage_ecran_normal" src="https://user-images.githubusercontent.com/44727542/95489461-eba87f00-0964-11eb-9469-597fe15ed65c.png">

Full screen
<img width="516" alt="Affichage_full_screen" src="https://user-images.githubusercontent.com/44727542/95489463-ec411580-0964-11eb-851c-e0e075849886.png">

**Comment by OllisGit** [comment]
Hi @skimaniac ,

I could reproduce the issue on my mac with safari, but it didnt' appear with chrome. The layout is broken, but the save button works.
In need to analyse this. In the meantime, try to switch to an other browser or change the resolution.

**Comment by OllisGit** [comment]
fyi: I did a small improvement maybe this will fix the issue on your side. It will be in the next release.

PS. Sorry, for being late to the party, but I made a "Octoprint sabatical" (no coding, no printing) the last months.

**Comment by OllisGit** [comment]
Hi, @skimaniac,

release 1.3.0 is out, please test and give feedback.

Thx, in advance
Olli
