### ISSUE TITLE
WARNING: Filament prediction not possible! One of the needed fields are not a number in Spool

### ISSUE THREAD

**Issue by AndersonGER** [OllisGit/OctoPrint-SpoolManager#72]
Hello,

i use the Plugin since a few Days, and insert all my Spools already.
When i try to print, i got the Issue above displayed.
I´ve already had a look @_♦ https://bitfab.io/blog/3d-printing-materials-densities/_ to improve that i got all Fields filled correctly, but it seems something is still wrong.

Can you  please help me to identify my fault?
My Fields are actual filled like this:
 
![image](https://user-images.githubusercontent.com/72657006/95655772-edf80e00-0b09-11eb-814e-13d1c51a8593.png)

Best Regards and lot of thx for your help
Anderson

**Comment by skimaniac** [comment]
you must not put a comma (1,75. 0,1) for the decimal, you must use the dot (1.75  0.1)
<img width="423" alt="Capture d’écran, le 2020-10-10 à 10 25 14" src="https://user-images.githubusercontent.com/44727542/95657604-554e9780-0ae3-11eb-90b9-2af7a39fbd7c.png">
.

**Comment by AndersonGER** [comment]
Hello Skimanic,

this fixed my Problem, thank you very much :)

Best regards from Germany
Anderson
