### ISSUE TITLE
Empty spool weight not taken into account

### ISSUE THREAD

**Issue by wernight** [OllisGit/OctoPrint-SpoolManager#89]
![image](https://user-images.githubusercontent.com/145667/102072781-a55b1a80-3e02-11eb-947b-a7d61cb873fc.png)

See above: 1366 - 415.7 = 950.3.

It should do:  1366 - 415.7 - 360 = 590.3.

Also changing the spool empty weight (currently 360 g) has no effect on the percentage used indicated.

**Comment by JoeThompsonGitHub** [comment]
I second this issue. Please can this be resolved as its giving an incorrect reading.

**Comment by OllisGit** [comment]
Closed: Duplicated issue, see #64, #79
PS. Sorry, for being late to the party, but I made a "Octoprint sabatical" (no coding, no printing) the last months.
