### ISSUE TITLE
Used filament % is not displayed

### ISSUE THREAD

**Issue by d4rken** [OllisGit/OctoPrint-SpoolManager#9]
On 1.0.0-RC2 and Octoprint 1.4.0.

After adding a small it does not display the remaining % in the spool list.

![Screenshot from 2020-07-17 09-19-21](https://user-images.githubusercontent.com/1439229/87759519-bc272200-c80e-11ea-93b8-4ed0796b97c3.png)
![Screenshot from 2020-07-17 09-18-42](https://user-images.githubusercontent.com/1439229/87759520-bd584f00-c80e-11ea-8b5f-9be67d588053.png)

**Comment by OllisGit** [comment]
Hi @d4rken ,

it is implemented in RC3.

Please test and give feedback.

Thx, in advance
Olli

**Comment by d4rken** [comment]
Works :+1: 

![Screenshot from 2020-07-22 17-48-14](https://user-images.githubusercontent.com/1439229/88198073-9a310380-cc43-11ea-97c8-4a953f788847.png)
