### ISSUE TITLE
[Feature Request] Ability to manually add usage

### ISSUE THREAD

**Issue by RussPitcher** [OllisGit/OctoPrint-SpoolManager#91]
It would be useful to be able to manually 'use' filament by entering # mm/metres used for situations where you might clip off a length from a spool or such like.  I know I can manually edit the weight/length used fields but it would be simpler to be able to enter a length into a box and have the plugin calculate the changes.

**Comment by OllisGit** [comment]
Closed: Duplicated issue, see #79, #64
PS. Sorry, for being late to the party, but I made a "Octoprint sabatical" (no coding, no printing) the last months.
