### ISSUE TITLE
[Feature Request] Usage History

### ISSUE THREAD

**Issue by Yang-Richard** [OllisGit/OctoPrint-SpoolManager#92]
It would be cool to see a brief history of usage for each spool, showing the prints that were done with that spool (date, duration, length, etc...). Just a simple way to get a short history of the spools and when they were last in use.

**Comment by OllisGit** [comment]
Hi @Yang-Richard,

this is planed after the integration with the PrintJobHistory-Plugin is done.

PS. Sorry, for being late to the party, but I made a "Octoprint sabatical" (no coding, no printing) the last months.

**Comment by OllisGit** [comment]
It is definitely planed  to do this. It is already planed (see backlog).

Closed, because I need to cleanup the issue-tracker.
