### ISSUE TITLE
[FR] how to edit vendors? (default catalogs)

### ISSUE THREAD

**Issue by coolduke666** [OllisGit/OctoPrint-SpoolManager#94]
currently I dont see any option to edit vendors - especially annoying when you have a typo in the vendorsname when you type it in for the first time.

currently only fixable in the database or do I miss something?

otherwise great enhancement. 

download template from other users would also be nice to share print and bed temps :+1:

**Comment by OllisGit** [comment]
Hi @coolduke666,

good point...this feature is missing! 
It is now on my roadmap.

Please create a new issue for the second point ("download template") and explain it in a more detailed way (example, screenshot)

BR
Olli
